"""Asking the geometry questions - ray casts, nearest points, and what is on which face.

WHY THESE AND WHY FIRST. This module was not chosen from a wishlist. It was chosen by counting what
real scripts actually escaped to run_python for: of 21 escapes in one day's work, 13 were RAY
CASTING and 15 were reading PER-FACE MATERIAL. Those two absences account for nearly every escape,
which makes them worth more than any number of features nobody reached for.

run_python is the arbitrary-code switch a user may well have turned off, so an addon that cannot
answer "what is at this point" or "which faces carry this material" is one that stops being usable
exactly when the work gets specific - finding a hole in a deck, locating a stairwell, selecting the
glass faces of a building.

=============================================================================
THE COORDINATE SPACE IS THE WHOLE CORRECTNESS STORY
=============================================================================
obj.ray_cast and obj.closest_point_on_mesh take and return the object's LOCAL space. A caller who
hands them world coordinates gets a miss, or worse a hit somewhere plausible and wrong, with
nothing anywhere saying so - and a moved, rotated or scaled object is the normal case, not the
exception. So this op takes WORLD coordinates, converts in, and converts back out. The space is
named in the response rather than assumed.

AND A NORMAL IS NOT A POINT. Transforming a normal by matrix_world is correct only while the scale
is uniform; under non-uniform scale it skews, and the result still looks like a unit-ish vector
pointing roughly the right way. Normals go through the INVERSE TRANSPOSE of the 3x3, which is the
one line in this file most likely to be got wrong by someone reimplementing it in a hurry.

=============================================================================
EVALUATED, NOT BASE, GEOMETRY
=============================================================================
scene.ray_cast works on the depsgraph, so it hits what is actually THERE - subdivided, displaced,
mirrored, generated by geometry nodes. obj.ray_cast works on the object's own mesh, which is the
cage. Those are different questions and both are legitimate, so the response says which one was
asked and the object form reports whether the object has modifiers that make them differ.
"""
import math

import bmesh
import bpy
import mathutils
import mathutils.bvhtree

from .ops_common import (MifOpError, get_object, reject_unknown, rnd, take, take_bool, take_float,
                         take_int)

_RAY_KEYS = {"origin", "direction", "target", "object", "name", "distance", "evaluated"}
# NO "name" ALIAS HERE. object is required and unambiguous, and param_reach flagged the alias
# as an accepted key no MCP tool can send. ray_cast and face_info keep theirs because both
# take the object OPTIONALLY, where a second spelling earns its place.
_NEAR_KEYS = {"object", "point", "distance"}
_FACE_KEYS = {"object", "name", "material", "slot", "indices", "limit", "withFaces",
              "evaluated"}

_DEFAULT_FACE_LIMIT = 200


def _vec(params, key, required=False, default=None):
    raw = params.get(key)
    if raw is None:
        if required:
            raise MifOpError("'%s' is required and must be [x,y,z]." % key)
        return None if default is None else mathutils.Vector(default)
    if isinstance(raw, dict):
        try:
            return mathutils.Vector((float(raw["x"]), float(raw["y"]), float(raw["z"])))
        except (KeyError, TypeError, ValueError):
            raise MifOpError("'%s' as an object needs x, y and z, got %r." % (key, raw))
    if not isinstance(raw, (list, tuple)) or len(raw) < 3:
        raise MifOpError("'%s' must be [x,y,z] or {x,y,z}, got %r." % (key, raw))
    try:
        return mathutils.Vector((float(raw[0]), float(raw[1]), float(raw[2])))
    except (TypeError, ValueError):
        raise MifOpError("'%s' must be three numbers, got %r." % (key, raw))


def _normal_to_world(obj, local_normal):
    """A normal from object space to world space.

    THE INVERSE TRANSPOSE, not matrix_world. Multiplying a normal by the object matrix is only
    correct while the scale is uniform; under non-uniform scale it SKEWS, and what comes out is
    still a plausible-looking vector pointing roughly the right way - so the error survives every
    eyeball check and shows up later as lighting or alignment that is subtly wrong.
    """
    m = obj.matrix_world.inverted_safe().transposed().to_3x3()
    return (m @ local_normal).normalized()


def op_ray_cast(params):
    """Fire a ray and report what it hits - in WORLD coordinates, both ways.

    THE SINGLE MOST-ESCAPED-TO OPERATION. Counted rather than guessed: 13 of 21 run_python escapes
    in one day were ray casts. It is what answers "what is at this point", "what is under it", "is
    anything across this edge" - the questions every layout, hard-surface and level job is built on.

    TWO FORMS, AND THEY ANSWER DIFFERENT QUESTIONS:
      no `object`   the whole scene, through the depsgraph - so it hits what is actually THERE:
                    subdivided, displaced, mirrored, generated by geometry nodes.
      `object`      that object only. Its own mesh by default, or its evaluated one with
                    evaluated:true. The difference matters the moment the object has a modifier,
                    and the response says which was used.

    COORDINATES ARE WORLD IN AND WORLD OUT. obj.ray_cast is LOCAL on both sides, and handing it
    world coordinates yields a miss or a plausible wrong hit with nothing to say so - a moved or
    rotated object being the normal case. The conversion happens here.

    params:
      origin [x,y,z]      required, world space
      direction [x,y,z]   required unless `target` is given. Need not be normalised.
      target [x,y,z]      cast TOWARDS this point instead of giving a direction
      object / name (str) restrict the cast to one object
      distance (float)    maximum range. Default unlimited.
      evaluated (bool)    object form only - cast against the modifier result. Default false.
    """
    reject_unknown(params, _RAY_KEYS, "ray_cast")
    origin = _vec(params, "origin", required=True)
    target = _vec(params, "target")
    direction = _vec(params, "direction")
    if target is not None and direction is not None:
        raise MifOpError("pass direction OR target, not both - target IS a direction, expressed "
                         "from the origin.")
    if target is None and direction is None:
        raise MifOpError("'direction' is required, or 'target' to cast towards a point.")
    if target is not None:
        direction = target - origin
    if direction.length == 0.0:
        raise MifOpError("the direction has zero length%s - a ray with no direction hits nothing."
                         % (" (target is the origin)" if target is not None else ""))
    direction = direction.normalized()

    distance = take_float(params, "distance", default=None)
    if distance is not None and distance <= 0.0:
        raise MifOpError("distance must be greater than 0, got %g." % distance)
    limit = distance if distance is not None else 1.0e38

    name = take(params, "object", "name", kind=str)
    # THE OBJECT IS VALIDATED BEFORE THE DEPSGRAPH IS ASKED FOR. evaluated_depsgraph_get()
    # forces an evaluation of the whole scene, which is real work to do on the way to
    # refusing - and this op is called in loops, where "cheap when it fails" is not a
    # nicety. Found by a check asserting the refusal rather than by reading.
    obj = None
    if name:
        obj = get_object(name)
        if obj.type != "MESH":
            raise MifOpError("'%s' is a %s. Only a MESH can be ray cast against directly; "
                             "omit 'object' to cast against the whole scene."
                             % (name, obj.type))
    depsgraph = bpy.context.evaluated_depsgraph_get()

    if obj is None:
        hit, loc, nrm, index, obj, _mat = bpy.context.scene.ray_cast(
            depsgraph, origin, direction, distance=limit)
        out = {
            "ok": True,
            "hit": bool(hit),
            "space": "WORLD",
            "against": "scene (evaluated depsgraph)",
            "origin": rnd(list(origin)),
            "direction": rnd(list(direction)),
        }
        if hit:
            out.update({
                "location": rnd(list(loc)),
                # ALREADY WORLD-SPACE. scene.ray_cast returns world coordinates and a world normal,
                # unlike the object form - so no conversion here, and doing one anyway would be the
                # mirror-image bug.
                "normal": rnd(list(nrm)),
                "faceIndex": int(index),
                "object": obj.name if obj else None,
                "distance": round((loc - origin).length, 6),
            })
        else:
            out["note"] = ("nothing was hit within %s. A scene cast uses the EVALUATED geometry, so "
                           "an object hidden from the viewport with hide_viewport is not in the "
                           "depsgraph and cannot be hit."
                           % ("%g units" % distance if distance else "any distance"))
        return out

    use_eval = take_bool(params, "evaluated", default=False)
    source = obj.evaluated_get(depsgraph) if use_eval else obj

    # WORLD IN, LOCAL FOR THE CALL. This is the conversion whose absence is the silent failure.
    inv = obj.matrix_world.inverted_safe()
    local_origin = inv @ origin
    local_dir = (inv.to_3x3() @ direction).normalized()

    hit, loc, nrm, index = source.ray_cast(local_origin, local_dir, distance=limit)
    modifiers = [m.name for m in obj.modifiers] if hasattr(obj, "modifiers") else []
    out = {
        "ok": True,
        "hit": bool(hit),
        "space": "WORLD",
        "against": "%s (%s geometry)" % (obj.name, "evaluated" if use_eval else "base"),
        "object": obj.name,
        "origin": rnd(list(origin)),
        "direction": rnd(list(direction)),
        "modifiers": modifiers,
    }
    if modifiers and not use_eval:
        out["note"] = ("'%s' has %d modifier(s) and this cast used its BASE mesh, so the surface "
                       "hit is the cage rather than what renders. Pass evaluated:true for the "
                       "modifier result." % (obj.name, len(modifiers)))
    if hit:
        world_loc = obj.matrix_world @ loc
        out.update({
            "location": rnd(list(world_loc)),
            "normal": rnd(list(_normal_to_world(obj, nrm))),
            "localLocation": rnd(list(loc)),
            "faceIndex": int(index),
            "distance": round((world_loc - origin).length, 6),
        })
    elif "note" not in out:
        out["note"] = "the ray missed '%s'." % obj.name
    return out


def op_closest_point(params):
    """The nearest point ON a mesh to a point in space - "what is under it", without a direction.

    The other half of ray_cast, and the one to reach for when there is no obvious direction to cast
    in: snapping something to a surface, measuring clearance, finding which face an object sits over.

    WORLD IN, WORLD OUT, for the same reason and with the same conversion. closest_point_on_mesh is
    local on both sides.

    params:
      object / name (str)   required, must be a MESH
      point [x,y,z]         required, world space
      distance (float)      maximum search range in LOCAL units. Default unlimited.
    """
    reject_unknown(params, _NEAR_KEYS, "closest_point_on_mesh")
    # ASSIGNED FIRST, not nested inside get_object. Every other op in this addon reads its
    # aliases into a variable, and param_reach resolves them from that form - nested, the "name"
    # alias reads as a parameter no MCP tool can send. Consistency here is not cosmetic.
    want = take(params, "object", required=True, kind=str)
    obj = get_object(want)
    if obj.type != "MESH":
        raise MifOpError("'%s' is a %s, and only a MESH has a surface to be near."
                         % (obj.name, obj.type))
    point = _vec(params, "point", required=True)
    distance = take_float(params, "distance", default=None)
    if distance is not None and distance <= 0.0:
        raise MifOpError("distance must be greater than 0, got %g." % distance)

    if not obj.data.polygons:
        raise MifOpError("'%s' has no faces, so there is no surface to be close to. It has %d "
                         "vertice(s)." % (obj.name, len(obj.data.vertices)))

    inv = obj.matrix_world.inverted_safe()
    local_point = inv @ point
    args = (local_point,) if distance is None else (local_point, distance)
    found, loc, nrm, index = obj.closest_point_on_mesh(*args)

    out = {
        "ok": True,
        "found": bool(found),
        "space": "WORLD",
        "object": obj.name,
        "point": rnd(list(point)),
    }
    if found:
        world_loc = obj.matrix_world @ loc
        out.update({
            "location": rnd(list(world_loc)),
            "normal": rnd(list(_normal_to_world(obj, nrm))),
            "localLocation": rnd(list(loc)),
            "faceIndex": int(index),
            "distance": round((world_loc - point).length, 6),
            # THE SIGN IS THE USEFUL PART. Positive means the query point is on the outside of that
            # face, negative means behind it - which is how "is this inside the mesh" gets answered
            # without a second cast.
            "signedOffset": round((point - world_loc).dot(_normal_to_world(obj, nrm)), 6),
        })
    else:
        out["note"] = ("no point within %g units of the query point." % distance if distance
                       else "closest_point_on_mesh found nothing, which for an unlimited search "
                            "means the mesh has no usable surface.")
    return out


def op_face_info(params):
    """Which faces carry which material, how many, and where they are.

    THE SECOND MOST-ESCAPED-TO QUESTION, counted rather than guessed: 15 of one day's 21 run_python
    escapes were reading per-face material. And it is a pure read/write asymmetry -
    assign_material_to_faces can WRITE that relation and nothing anywhere could read it back, so
    every "operate on just the glass faces" job had to leave the typed path entirely.

    AGGREGATE FIRST, DETAIL ON REQUEST. A production mesh has hundreds of thousands of faces, so
    returning them all is not a service; the per-slot counts, areas and bounding boxes answer most
    of the question in a fixed-size response, and withFaces asks for rows only once the caller knows
    which slot they care about.

    THE BOUNDING BOX IS REPORTED IN BOTH SPACES. Local is what the mesh data holds; world is what
    anybody positioning something against it needs, and deriving one from the other requires the
    object matrix that a caller reading this remotely does not have. Reporting only local would push
    the same transform mistake this module's ray_cast exists to prevent onto every caller.

    EMPTY SLOTS ARE REPORTED, and that is deliberate: a material slot with no faces is the state
    assign_material_to_faces leaves behind when the wrong index was used, and it is invisible from
    the material list, which shows the slot as present and assigned.

    params:
      object / name (str)     required, must be a MESH
      material (str)          only faces using this material
      slot (int)              only faces in this material slot index
      indices (list[int])     only these face indices
      limit (int)             maximum face rows returned. Default 200.
      withFaces (bool)        include per-face rows at all. Default false.
      evaluated (bool)        read the MODIFIER RESULT rather than the base mesh. Default false -
                              the base mesh is what assign_material_to_faces writes to, so it is
                              what a caller comparing against a write needs.
    """
    reject_unknown(params, _FACE_KEYS, "face_info")
    want = take(params, "object", "name", required=True, kind=str)
    obj = get_object(want)
    if obj.type != "MESH":
        raise MifOpError("'%s' is a %s and has no faces." % (obj.name, obj.type))

    # EVERY PARAMETER IS CHECKED BEFORE ANY MESH DATA IS TOUCHED. Reading material_slots, or
    # evaluating the depsgraph, on the way to refusing a bad argument combination is work done for
    # nothing - and on a heavy mesh it is a lot of it, in an op meant to be called in a loop. Only
    # the checks that NEED the mesh (does that slot exist, is that face index in range) happen
    # after. Found by checks asserting these refusals, not by reading the code.
    want_mat = take(params, "material", kind=str)
    want_slot = params.get("slot")
    indices = params.get("indices")
    if want_mat is not None and want_slot is not None:
        raise MifOpError("pass material OR slot, not both - a material can occupy more than one "
                         "slot, so the two can disagree and only one of them could win.")
    if indices is not None and not isinstance(indices, (list, tuple)):
        raise MifOpError("'indices' must be a list of face indices, got %s."
                         % type(indices).__name__)
    limit = params.get("limit")
    limit = _DEFAULT_FACE_LIMIT if limit is None else int(limit)
    if limit < 0:
        raise MifOpError("'limit' cannot be negative, got %d." % limit)
    with_faces = take_bool(params, "withFaces", default=False)

    use_eval = take_bool(params, "evaluated", default=False)
    if use_eval:
        depsgraph = bpy.context.evaluated_depsgraph_get()
        mesh = obj.evaluated_get(depsgraph).data
    else:
        mesh = obj.data

    slots = [s.material.name if s.material else None for s in obj.material_slots]
    slot_filter = None
    if want_mat is not None:
        matching = [i for i, n in enumerate(slots) if n == want_mat]
        if not matching:
            raise MifOpError("'%s' has no material slot holding '%s'. Its slots are: %s."
                             % (obj.name, want_mat,
                                ", ".join("%d=%s" % (i, n or "<empty>")
                                          for i, n in enumerate(slots)) or "<none>"))
        slot_filter = set(matching)
    elif want_slot is not None:
        try:
            want_slot = int(want_slot)
        except (TypeError, ValueError):
            raise MifOpError("'slot' must be an integer index, got %r." % (want_slot,))
        if not 0 <= want_slot < max(len(slots), 1):
            raise MifOpError("slot %d is out of range - '%s' has %d slot(s)."
                             % (want_slot, obj.name, len(slots)))
        slot_filter = {want_slot}

    index_filter = None
    if indices is not None:
        try:
            index_filter = {int(i) for i in indices}
        except (TypeError, ValueError):
            raise MifOpError("'indices' must be whole numbers.")
        highest = len(mesh.polygons) - 1
        bad = sorted(i for i in index_filter if i < 0 or i > highest)
        if bad:
            raise MifOpError("face index %s is out of range - '%s' has %d face(s), so the highest "
                             "index is %d." % (bad[0], obj.name, len(mesh.polygons), highest))

    mw = obj.matrix_world
    per_slot = {}
    rows = []
    matched = 0
    for poly in mesh.polygons:
        si = poly.material_index
        if slot_filter is not None and si not in slot_filter:
            continue
        if index_filter is not None and poly.index not in index_filter:
            continue
        matched += 1
        agg = per_slot.setdefault(si, {"faceCount": 0, "area": 0.0, "lo": None, "hi": None})
        agg["faceCount"] += 1
        agg["area"] += float(poly.area)
        for v in poly.vertices:
            co = mesh.vertices[v].co
            if agg["lo"] is None:
                agg["lo"] = [co[0], co[1], co[2]]
                agg["hi"] = [co[0], co[1], co[2]]
            else:
                for a in range(3):
                    agg["lo"][a] = min(agg["lo"][a], co[a])
                    agg["hi"][a] = max(agg["hi"][a], co[a])
        if with_faces and len(rows) < limit:
            centre = poly.center
            rows.append({
                "index": poly.index,
                "slot": si,
                "material": slots[si] if si < len(slots) else None,
                "area": round(float(poly.area), 6),
                "vertexCount": len(poly.vertices),
                "centerWorld": rnd(list(mw @ centre)),
                "normalWorld": rnd(list(_normal_to_world(obj, poly.normal))),
                "smooth": bool(poly.use_smooth),
            })

    slot_rows = []
    for si in range(max(len(slots), (max(per_slot) + 1) if per_slot else 0)):
        agg = per_slot.get(si)
        row = {
            "slot": si,
            "material": slots[si] if si < len(slots) else None,
            "faceCount": agg["faceCount"] if agg else 0,
            "area": round(agg["area"], 6) if agg else 0.0,
        }
        if agg and agg["lo"] is not None:
            lo = mathutils.Vector(agg["lo"])
            hi = mathutils.Vector(agg["hi"])
            row["bboxLocal"] = {"min": rnd(list(lo)), "max": rnd(list(hi)),
                                "size": rnd([hi[a] - lo[a] for a in range(3)])}
            # THE WORLD BOX IS BUILT FROM ALL EIGHT CORNERS, not from transforming min and max.
            # Transforming two opposite corners is correct only for an axis-aligned matrix; under
            # any rotation it produces a box that is the wrong size and, worse, plausible.
            corners = [mw @ mathutils.Vector((lo[0] if i & 1 else hi[0],
                                              lo[1] if i & 2 else hi[1],
                                              lo[2] if i & 4 else hi[2])) for i in range(8)]
            wlo = [min(c[a] for c in corners) for a in range(3)]
            whi = [max(c[a] for c in corners) for a in range(3)]
            row["bboxWorld"] = {"min": rnd(wlo), "max": rnd(whi),
                                "size": rnd([whi[a] - wlo[a] for a in range(3)])}
        slot_rows.append(row)

    empty = [r["slot"] for r in slot_rows if r["faceCount"] == 0 and r["material"]]
    out = {
        "ok": True,
        "object": obj.name,
        "geometry": "evaluated" if use_eval else "base",
        "faceCount": len(mesh.polygons),
        "facesMatched": matched,
        "materialSlots": slot_rows,
        "slotsWithNoFaces": empty,
    }
    if with_faces:
        out["faces"] = rows
        out["facesReturned"] = len(rows)
        # NO SILENT TRUNCATION. A caller who gets 200 rows out of 40000 and is not told has a
        # sample they will treat as the set.
        out["facesTruncated"] = matched > len(rows)
        if out["facesTruncated"]:
            out["truncationNote"] = ("%d face(s) matched and %d were returned - raise limit, or "
                                     "filter by material or slot." % (matched, len(rows)))
    if empty:
        out["emptySlotNote"] = ("slot(s) %s hold a material and NO faces. That is what "
                                "assign_material_to_faces leaves behind when the wrong slot index "
                                "was used, and it is invisible from the material list, which shows "
                                "the slot as present." % ", ".join(str(s) for s in empty))
    return out


_SELF_KEYS = {"object", "name", "material", "slot", "axis", "direction", "angle", "minArea",
              "maxArea", "insideBox", "boxMin", "boxMax", "smooth", "limit", "evaluated",
              "requireAll"}

_AXES = {"X": (1.0, 0.0, 0.0), "-X": (-1.0, 0.0, 0.0),
         "Y": (0.0, 1.0, 0.0), "-Y": (0.0, -1.0, 0.0),
         "Z": (0.0, 0.0, 1.0), "-Z": (0.0, 0.0, -1.0)}


def op_select_faces(params):
    """Find the faces matching a description - the thing every "operate on just these" job needed.

    THE MISSING HALF OF assign_material_to_faces. That op takes face INDICES, and until now the only
    way to work out which indices you wanted was raw Python: iterate the polygons, test the material
    or the normal or the area, collect the numbers. So the typed path could ACT on a face set it
    could not COMPUTE, and select_edges had no counterpart for faces.

    READ-ONLY, like select_edges: nothing is written and no selection state is touched. What comes
    back is a list of indices to hand to another op, plus the counts to sanity-check it with.

    CRITERIA COMBINE WITH AND BY DEFAULT, which is what "the upward-facing glass faces bigger than
    a metre" means. requireAll:false switches to OR for the cases where it does not.

    THE NORMAL TEST IS IN WORLD SPACE, through the inverse transpose - a face pointing up in local
    space on a rotated object does not point up in the world, and "which faces are the floor" is a
    world-space question every time it is asked. The angle is a full cone half-angle in DEGREES,
    because nobody thinks about floors in radians.

    THE BOX TEST IS ALSO WORLD SPACE and uses the face CENTRE, which is a deliberate simplification
    worth naming: a large face straddling the boundary is in or out by where its middle falls. It is
    the behaviour that makes "the faces in this room" work, and it is not the same as "every face
    fully inside the box".

    params:
      object / name (str)     required, must be a MESH
      material (str)          faces using this material
      slot (int)              faces in this material slot
      axis (str)              X | -X | Y | -Y | Z | -Z - faces pointing this way in WORLD space
      direction [x,y,z]       an arbitrary world direction, instead of axis
      angle (float)           cone half-angle in DEGREES around axis/direction. Default 45.
      minArea / maxArea       face area, in the object's own units
      insideBox / boxMin+Max  a world-space box; a face is in if its CENTRE is
      smooth (bool)           faces flagged smooth, or flat
      requireAll (bool)       AND all criteria (default) or OR them
      limit (int)             cap on returned indices. The COUNT is always exact.
      evaluated (bool)        test the modifier result rather than the base mesh
    """
    reject_unknown(params, _SELF_KEYS, "select_faces")
    want = take(params, "object", "name", required=True, kind=str)
    obj = get_object(want)
    if obj.type != "MESH":
        raise MifOpError("'%s' is a %s and has no faces to select." % (obj.name, obj.type))

    # EVERY CRITERION PARSED AND VALIDATED FIRST, before a single polygon is touched. On a heavy
    # mesh the walk is the expensive part, and a typo in the fourth criterion should cost nothing.
    want_mat = take(params, "material", kind=str)
    want_slot = params.get("slot")
    if want_mat is not None and want_slot is not None:
        raise MifOpError("pass material OR slot, not both - a material can occupy more than one "
                         "slot, so the two can disagree.")
    axis = take(params, "axis", kind=str)
    direction = _vec(params, "direction")
    if axis and direction is not None:
        raise MifOpError("pass axis OR direction, not both - axis IS a direction, named.")
    if axis:
        key = str(axis).upper()
        if key not in _AXES:
            raise MifOpError("axis must be one of %s, got '%s'."
                             % (", ".join(sorted(_AXES)), axis))
        direction = mathutils.Vector(_AXES[key])
    if direction is not None:
        if direction.length == 0.0:
            raise MifOpError("the direction has zero length - it selects nothing.")
        direction = direction.normalized()
    angle_deg = take_float(params, "angle", default=45.0)
    if direction is not None and not 0.0 < angle_deg <= 180.0:
        raise MifOpError("angle must be greater than 0 and at most 180 degrees, got %g. It is a "
                         "cone HALF-angle, so 90 is a whole hemisphere." % angle_deg)
    cos_limit = math.cos(math.radians(angle_deg))

    min_area = take_float(params, "minArea", default=None)
    max_area = take_float(params, "maxArea", default=None)
    if min_area is not None and max_area is not None and max_area < min_area:
        raise MifOpError("maxArea %g is below minArea %g - nothing can match."
                         % (max_area, min_area))

    box_min = _vec(params, "boxMin")
    box_max = _vec(params, "boxMax")
    inside = params.get("insideBox")
    if inside is not None:
        if not isinstance(inside, (list, tuple)) or len(inside) != 2:
            raise MifOpError("'insideBox' must be [[minX,minY,minZ],[maxX,maxY,maxZ]]; or use "
                             "boxMin and boxMax.")
        box_min = _vec({"boxMin": inside[0]}, "boxMin")
        box_max = _vec({"boxMax": inside[1]}, "boxMax")
    if (box_min is None) != (box_max is None):
        raise MifOpError("a box needs BOTH corners - got only %s."
                         % ("boxMin" if box_min is not None else "boxMax"))
    if box_min is not None:
        # NORMALISED RATHER THAN REFUSED. A box given corner-first-any-order is a natural thing to
        # write and there is exactly one sensible reading of it.
        lo = mathutils.Vector([min(box_min[i], box_max[i]) for i in range(3)])
        hi = mathutils.Vector([max(box_min[i], box_max[i]) for i in range(3)])
        box_min, box_max = lo, hi

    smooth = params.get("smooth")
    limit = take_int(params, "limit", default=1024)
    if limit < 0:
        raise MifOpError("'limit' cannot be negative, got %d. The count is always exact; this "
                         "caps only how many indices come back." % limit)
    require_all = take_bool(params, "requireAll", default=True)

    tests = [t for t in (want_mat is not None or want_slot is not None,
                         direction is not None, min_area is not None, max_area is not None,
                         box_min is not None, smooth is not None) if t]
    if not tests:
        raise MifOpError("no criteria given - pass at least one of material, slot, axis, "
                         "direction, minArea, maxArea, insideBox or smooth. Without one this "
                         "would return every face, which face_info already does.")

    use_eval = take_bool(params, "evaluated", default=False)
    mesh = (obj.evaluated_get(bpy.context.evaluated_depsgraph_get()).data if use_eval
            else obj.data)
    slots = [s.material.name if s.material else None for s in obj.material_slots]
    slot_filter = None
    if want_mat is not None:
        matching = [i for i, n in enumerate(slots) if n == want_mat]
        if not matching:
            raise MifOpError("'%s' has no material slot holding '%s'. Its slots are: %s."
                             % (obj.name, want_mat,
                                ", ".join("%d=%s" % (i, n or "<empty>")
                                          for i, n in enumerate(slots)) or "<none>"))
        slot_filter = set(matching)
    elif want_slot is not None:
        try:
            want_slot = int(want_slot)
        except (TypeError, ValueError):
            raise MifOpError("'slot' must be an integer index, got %r." % (want_slot,))
        if not 0 <= want_slot < max(len(slots), 1):
            raise MifOpError("slot %d is out of range - '%s' has %d slot(s)."
                             % (want_slot, obj.name, len(slots)))
        slot_filter = {want_slot}

    mw = obj.matrix_world
    hits, per_reason = [], {}
    for poly in mesh.polygons:
        results = []
        if slot_filter is not None:
            results.append(("material", poly.material_index in slot_filter))
        if direction is not None:
            world_n = _normal_to_world(obj, poly.normal)
            results.append(("direction", world_n.dot(direction) >= cos_limit))
        if min_area is not None:
            results.append(("minArea", poly.area >= min_area))
        if max_area is not None:
            results.append(("maxArea", poly.area <= max_area))
        if box_min is not None:
            centre = mw @ poly.center
            results.append(("insideBox",
                            all(box_min[i] <= centre[i] <= box_max[i] for i in range(3))))
        if smooth is not None:
            results.append(("smooth", bool(poly.use_smooth) == bool(smooth)))
        for label, passed in results:
            if passed:
                per_reason[label] = per_reason.get(label, 0) + 1
        if (all(r[1] for r in results) if require_all else any(r[1] for r in results)):
            hits.append(poly.index)

    out = {
        "ok": True,
        "object": obj.name,
        "geometry": "evaluated" if use_eval else "base",
        "faceCount": len(mesh.polygons),
        # EXACT, ALWAYS. The index list is capped and the count never is - a caller sizing a job
        # off a truncated list would plan for a fraction of the work.
        "matched": len(hits),
        "indices": hits[:limit],
        # A COUNT, NOT A CLAIM. This was an indicesTruncated boolean, which asserts
        # something about the response that no offline check can reach - the same objection
        # that retired outputPathsTruncated from render_animation. indicesReturned against
        # matched says the identical thing as two facts a caller can compare, and neither
        # of them can be wrong without the numbers being wrong.
        "indicesReturned": len(hits[:limit]),
        "mode": "AND" if require_all else "OR",
        "criteria": sorted(per_reason),
        # PER-CRITERION COUNTS, which is what turns "it matched nothing" into an answer. With AND
        # over four tests, knowing that three matched thousands and one matched zero names the
        # culprit immediately.
        "matchedPerCriterion": per_reason,
        "space": "WORLD (normals and the box)",
    }
    if not hits:
        zero = [k for k, v in per_reason.items() if v == 0] or \
               [k for k in ("material", "direction", "minArea", "maxArea", "insideBox", "smooth")
                if k not in per_reason]
        out["note"] = ("nothing matched. Per-criterion counts are above; %s matched no face at "
                       "all, which is where to look first."
                       % (", ".join(zero) if zero else "no single criterion"))
    if box_min is not None:
        out["boxNote"] = ("a face is inside the box when its CENTRE is, so a large face straddling "
                          "the boundary is decided by its middle. That is what makes 'the faces in "
                          "this room' work and is not the same as 'entirely inside'.")
    return out


# ONE SPELLING FOR THE POINT. "planePoint" was a friendlier alias for planeCo and no MCP tool
# sent it, so it was an accepted key with no route to it. planeNormal survives because
# param_reach resolves it against planeNo, which it contains; planeCo and planePoint share
# no substring, so the alias could never have been reached.
_BISECT_KEYS = {"object", "name", "planeCo", "planeNo", "planeNormal", "axis",
                "clearInner", "clearOuter", "fill", "threshold"}
_SHADE_KEYS = {"object", "name", "smooth", "autoSmoothAngle", "indices", "weightedNormals",
               "weightedNormalsMode", "keepSharp"}

_BISECT_AXES = {"X": (1.0, 0.0, 0.0), "Y": (0.0, 1.0, 0.0), "Z": (0.0, 0.0, 1.0)}


def op_bisect_plane(params):
    """Cut a mesh with a plane - the one primitive operation that made a window possible.

    WHY THIS AND NOT bevel/boolean/separate/decimate. Those all exist here already; bisect does not,
    and it is the FUNDAMENTAL "cut at a plane" that the others are not. A boolean needs a second
    object to cut with, which means authoring a cutter, positioning it and cleaning it up
    afterwards, for what is one plane. Bisect takes the plane directly.

    IT WORKS THROUGH bmesh, NOT bpy.ops.mesh.bisect. The operator needs EDIT mode and a selection,
    which from a socket call means a mode switch that can strand every op after it (see
    create_armature). bmesh.ops.bisect_plane does the same work on the mesh data with no mode
    change at all.

    THE PLANE IS GIVEN IN WORLD SPACE and converted in, because "cut at z=2.4" is a world statement
    every time somebody makes it, and handing a local plane to a moved object cuts somewhere else
    entirely - silently, since a cut that missed looks exactly like a cut that did nothing.

    params:
      object / name (str)          required, must be a MESH
      planeCo [x,y,z]              a point ON the plane, world space. Required.
      planeNo / planeNormal        the plane's normal, world space
      axis (str)                   X | Y | Z instead of a normal - the common case
      clearInner (bool)            delete the geometry on the normal's negative side
      clearOuter (bool)            delete the geometry on the positive side
      fill (bool)                  cap the hole the cut leaves. Default true when clearing.
      threshold (float)            distance under which a vertex counts as ON the plane
    """
    reject_unknown(params, _BISECT_KEYS, "bisect_plane")
    want = take(params, "object", "name", required=True, kind=str)
    obj = get_object(want)
    if obj.type != "MESH":
        raise MifOpError("'%s' is a %s and cannot be bisected." % (obj.name, obj.type))
    if obj.mode != "OBJECT":
        raise MifOpError("'%s' is in %s mode. Bisecting writes the mesh data directly and would "
                         "be overwritten when edit mode is left. NOTHING was changed."
                         % (obj.name, obj.mode))

    point = _vec(params, "planeCo", required=False)
    if point is None:
        raise MifOpError("'planeCo' is required - a point ON the cutting plane, in world space. "
                         "NOTHING was changed.")
    normal = _vec(params, "planeNo")
    if normal is None:
        normal = _vec(params, "planeNormal")
    axis = take(params, "axis", kind=str)
    if axis and normal is not None:
        raise MifOpError("pass axis OR a plane normal, not both. NOTHING was changed.")
    if axis:
        key = str(axis).upper()
        if key not in _BISECT_AXES:
            raise MifOpError("axis must be X, Y or Z, got '%s'. NOTHING was changed." % axis)
        normal = mathutils.Vector(_BISECT_AXES[key])
    if normal is None:
        raise MifOpError("give the plane a direction - 'axis' (X/Y/Z) or 'planeNo' [x,y,z]. "
                         "NOTHING was changed.")
    if normal.length == 0.0:
        raise MifOpError("the plane normal has zero length, which describes no plane. NOTHING was "
                         "changed.")
    normal = normal.normalized()

    clear_inner = take_bool(params, "clearInner", default=False)
    clear_outer = take_bool(params, "clearOuter", default=False)
    if clear_inner and clear_outer:
        raise MifOpError("clearInner AND clearOuter together delete everything on both sides of "
                         "the plane, leaving an empty mesh. If that is what you want, use "
                         "clear_mesh. NOTHING was changed.")
    fill = take_bool(params, "fill", default=clear_inner or clear_outer)
    threshold = take_float(params, "threshold", default=0.0001)
    if threshold < 0.0:
        raise MifOpError("threshold cannot be negative, got %g. NOTHING was changed." % threshold)

    # WORLD PLANE -> LOCAL. The point goes through the inverse matrix and the NORMAL through the
    # inverse transpose, for the reason ops_query's header gives: a normal is not a point, and
    # under non-uniform scale the difference is a plane tilted off where it was asked for.
    inv = obj.matrix_world.inverted_safe()
    local_co = inv @ point
    local_no = (obj.matrix_world.inverted_safe().transposed().to_3x3() @ normal).normalized()

    mesh = obj.data
    before = (len(mesh.vertices), len(mesh.edges), len(mesh.polygons))
    bm = bmesh.new()
    try:
        bm.from_mesh(mesh)
        geom = list(bm.verts) + list(bm.edges) + list(bm.faces)
        bmesh.ops.bisect_plane(bm, geom=geom, dist=threshold, plane_co=local_co,
                               plane_no=local_no, clear_inner=clear_inner,
                               clear_outer=clear_outer)
        if fill:
            # THE CUT LEAVES AN OPEN BOUNDARY when either side is cleared, and an unfilled one is
            # a hole - which renders as a black gap and exports as non-manifold. Filled from the
            # boundary edges the cut actually produced rather than from everything, or the fill
            # would bridge unrelated holes the mesh already had.
            edges = [e for e in bm.edges if len(e.link_faces) == 1]
            if edges:
                bmesh.ops.holes_fill(bm, edges=edges)
        bm.to_mesh(mesh)
        mesh.update()
    finally:
        bm.free()

    after = (len(mesh.vertices), len(mesh.edges), len(mesh.polygons))
    # THE POSTCONDITION IS THAT THE MESH MOVED. bisect_plane raises nothing when the plane misses
    # the geometry entirely - it reports success having changed not one vertex, which is
    # indistinguishable from a cut that worked until somebody looks.
    if after == before:
        raise MifOpError("the mesh is unchanged - %d verts, %d edges, %d faces before and after. "
                         "The plane almost certainly MISSED '%s' entirely: the point is given in "
                         "WORLD space, and its bounding box is %s to %s in world units. Nothing "
                         "was cut."
                         % (before[0], before[1], before[2], obj.name,
                            rnd(list(obj.matrix_world @ mathutils.Vector(obj.bound_box[0]))),
                            rnd(list(obj.matrix_world @ mathutils.Vector(obj.bound_box[6])))))
    return {
        "ok": True,
        "object": obj.name,
        "planeCo": rnd(list(point)),
        "planeNo": rnd(list(normal)),
        "space": "WORLD",
        "clearInner": clear_inner,
        "clearOuter": clear_outer,
        "filled": fill,
        "before": {"vertices": before[0], "edges": before[1], "faces": before[2]},
        "after": {"vertices": after[0], "edges": after[1], "faces": after[2]},
        "delta": {"vertices": after[0] - before[0], "edges": after[1] - before[1],
                  "faces": after[2] - before[2]},
    }


def op_set_shading(params):
    """Smooth or flat shading, the auto-smooth angle, and weighted normals.

    NOTHING HERE ADDRESSED SHADING AT ALL. Setting flat shading per polygon in a loop is raw Python,
    and hard-surface game assets need it constantly - it is the difference between a bevelled edge
    reading as a crease and reading as a smear.

    =========================================================================
    auto_smooth MOVED IN 4.1 AND THE OLD PROPERTY IS GONE
    =========================================================================
    Up to 4.0, mesh.use_auto_smooth plus mesh.auto_smooth_angle. From 4.1 both were REMOVED and
    replaced by a "Smooth by Angle" geometry-nodes modifier. This addon supports 3.6 through 5.0,
    so writing the old property on a 4.1+ build raises, and a version that caught the exception and
    moved on would report success having changed nothing - shading silently wrong on exactly the
    builds most people are using. Both routes are implemented and the response says which was taken.

    params:
      object / name (str)        required, must be a MESH
      smooth (bool)              smooth or flat, applied to every face or to `indices`
      indices (list[int])        only these faces. Omit for all of them.
      autoSmoothAngle (float)    DEGREES. Faces meeting at a sharper angle stay flat.
      weightedNormals (bool)     add a Weighted Normal modifier - the fix for a bevelled corner
                                 that shades wrong no matter what the smooth flags say
      weightedNormalsMode (str)  CORNER_ANGLE | FACE_AREA | FACE_AREA_WITH_ANGLE
      keepSharp (bool)           weighted normals: preserve edges marked sharp. Default true.
    """
    reject_unknown(params, _SHADE_KEYS, "set_shading")
    want = take(params, "object", "name", required=True, kind=str)
    obj = get_object(want)
    if obj.type != "MESH":
        raise MifOpError("'%s' is a %s and has no shading to set." % (obj.name, obj.type))
    mesh = obj.data

    smooth = params.get("smooth")
    angle = take_float(params, "autoSmoothAngle", default=None)
    weighted = params.get("weightedNormals")
    if smooth is None and angle is None and weighted is None:
        raise MifOpError("nothing to do - pass smooth, autoSmoothAngle or weightedNormals. "
                         "NOTHING was changed.")
    if angle is not None and not 0.0 <= angle <= 180.0:
        raise MifOpError("autoSmoothAngle is in DEGREES and must be 0-180, got %g. NOTHING was "
                         "changed." % angle)

    indices = params.get("indices")
    index_filter = None
    if indices is not None:
        if not isinstance(indices, (list, tuple)):
            raise MifOpError("'indices' must be a list of face indices, got %s. NOTHING was "
                             "changed." % type(indices).__name__)
        try:
            index_filter = {int(i) for i in indices}
        except (TypeError, ValueError):
            raise MifOpError("'indices' must be whole numbers. NOTHING was changed.")
        highest = len(mesh.polygons) - 1
        bad = sorted(i for i in index_filter if i < 0 or i > highest)
        if bad:
            raise MifOpError("face index %d is out of range - '%s' has %d face(s). NOTHING was "
                             "changed." % (bad[0], obj.name, len(mesh.polygons)))
        if smooth is None:
            raise MifOpError("'indices' selects which faces to flag, so it needs 'smooth'. "
                             "NOTHING was changed.")

    changed = 0
    if smooth is not None:
        want_smooth = take_bool(params, "smooth", default=True)
        for poly in mesh.polygons:
            if index_filter is not None and poly.index not in index_filter:
                continue
            if poly.use_smooth != want_smooth:
                changed += 1
            poly.use_smooth = want_smooth

    auto_route = None
    if angle is not None:
        if hasattr(mesh, "use_auto_smooth"):
            mesh.use_auto_smooth = True
            mesh.auto_smooth_angle = math.radians(angle)
            auto_route = "mesh.use_auto_smooth (Blender < 4.1)"
        else:
            # 4.1+ - a geometry-nodes modifier, added by the operator that owns the node group.
            # Doing it by hand would mean shipping a copy of Blender's own node tree.
            try:
                with bpy.context.temp_override(object=obj, active_object=obj,
                                               selected_objects=[obj],
                                               selected_editable_objects=[obj]):
                    bpy.ops.object.shade_auto_smooth(angle=math.radians(angle))
                auto_route = "Smooth by Angle modifier (Blender 4.1+)"
            except (RuntimeError, AttributeError) as exc:
                raise MifOpError("this Blender (%s) has neither mesh.use_auto_smooth nor a working "
                                 "object.shade_auto_smooth operator (%s), so the auto-smooth angle "
                                 "cannot be set. Any face flags requested WERE applied."
                                 % (bpy.app.version_string, exc))

    wn = None
    if weighted is not None:
        existing = next((m for m in obj.modifiers if m.type == "WEIGHTED_NORMAL"), None)
        if take_bool(params, "weightedNormals", default=True):
            mod = existing or obj.modifiers.new(name="MifWeightedNormal", type="WEIGHTED_NORMAL")
            mode = take(params, "weightedNormalsMode", kind=str)
            if mode:
                valid = {i.identifier
                         for i in mod.bl_rna.properties["mode"].enum_items}
                if str(mode).upper() not in valid:
                    raise MifOpError("weightedNormalsMode '%s' is not one this Blender offers. "
                                     "Valid: %s." % (mode, ", ".join(sorted(valid))))
                mod.mode = str(mode).upper()
            mod.keep_sharp = take_bool(params, "keepSharp", default=True)
            wn = {"modifier": mod.name, "mode": mod.mode, "keepSharp": bool(mod.keep_sharp)}
        elif existing is not None:
            obj.modifiers.remove(existing)
            wn = {"removed": True}
        else:
            wn = {"removed": False, "note": "there was no Weighted Normal modifier to remove."}

    mesh.update()
    smooth_faces = sum(1 for p in mesh.polygons if p.use_smooth)
    return {
        "ok": True,
        "object": obj.name,
        "faceCount": len(mesh.polygons),
        "facesChanged": changed,
        "smoothFaces": smooth_faces,
        "flatFaces": len(mesh.polygons) - smooth_faces,
        "autoSmoothAngle": angle,
        # WHICH ROUTE WAS TAKEN, because they are different mechanisms with different consequences:
        # the 4.1+ one adds a MODIFIER, which shows up in list_modifiers, applies in export, and can
        # be removed - none of which is true of the old property.
        "autoSmoothVia": auto_route,
        "weightedNormals": wn,
        "note": ("facesChanged is 0 - every face was already flagged that way, which is a no-op "
                 "rather than a failure.") if smooth is not None and changed == 0 else None,
    }

_OVERLAP_KEYS = {"a", "b", "objects", "tolerance", "maxSamples", "evaluated"}

_DEFAULT_OVERLAP_SAMPLES = 2000


def _world_bvh(obj, depsgraph, use_eval):
    """(BVHTree, sample points) for an object, both in WORLD space.

    NEVER BVHTree.FromObject, and that is the single most important line in this module.

    FromObject BUILDS THE TREE IN THE OBJECT'S LOCAL SPACE AND SILENTLY IGNORES matrix_world.
    Measured on 3.6.23, 4.4.0 and 5.0.1: two unit cubes FIVE UNITS APART report 2 overlap pairs
    through FromObject and 0 through this function. Two trees built that way are in two different
    coordinate frames, so every answer they give about each other is meaningless - and confidently
    so, since nothing raises and the pair list looks like a real result.

    FromObject on a NON-MESH object also SEGFAULTS Blender 3.6 outright - no traceback, no Python
    exception, the process is simply gone. Building from a bmesh avoids that entire failure mode
    rather than guarding it, which is why the type check below is belt and braces rather than the
    only thing standing between a caller and a dead process.

    THE SAMPLE POINTS ARE VERTICES *AND* FACE CENTROIDS. Vertices alone are not enough: two cubes
    overlapping by 0.1 scored 0 of 8 vertices inside on every version, because every vertex of the
    overlap region sits exactly ON the other surface where the inside test is ambiguous. Centroids
    sit strictly inside a face and settle it.
    """
    source = obj.evaluated_get(depsgraph) if use_eval else obj
    mesh = source.to_mesh()
    try:
        bm = bmesh.new()
        bm.from_mesh(mesh)
        # THE TRANSFORM IS THE WHOLE TRICK. to_mesh() returns LOCAL coordinates - vertex 0 of a cube
        # sitting at x=5 still reads (-1,-1,-1) - so without this both trees describe geometry at
        # the origin no matter where the objects actually are.
        bm.transform(obj.matrix_world)
        tree = mathutils.bvhtree.BVHTree.FromBMesh(bm)
        points = [v.co.copy() for v in bm.verts]
        points += [f.calc_center_median().copy() for f in bm.faces]
        bm.free()
        return tree, points
    finally:
        source.to_mesh_clear()


def _is_inside(tree, point, tol):
    """Is `point` strictly inside the closed surface `tree` describes?

    SIGNED DISTANCE TO THE NEAREST FACE, not ray parity. A parity test re-casts from just past each
    hit, and with a fixed small offset it silently returns the WRONG answer once geometry is away
    from the world origin: a 1-unit cube inside a 4-unit cube, both at z=200, scores 6 of 8 vertices
    inside instead of 8 of 8, because the offset vanishes into float32 at that magnitude. It fails
    quietly and plausibly, which is the worst way to fail.
    """
    location, normal, _index, _distance = tree.find_nearest(point)
    if location is None:
        return False
    return (point - location).dot(normal) < -tol


def op_objects_overlap(params):
    """Do two objects actually intersect - asked of the GEOMETRY, not of their bounding boxes.

    WHY THIS EXISTS. The question was being answered with axis-aligned bounding boxes in Python
    because there was no way to ask the real thing, and an AABB test says two objects overlap when
    they do not. Measured on all four builds: a 2m cube rotated 45 degrees about Z and a 1m cube at
    (1.45, 1.45, 0) have world AABBs that DO intersect, and geometry that does not touch at all -
    the diamond footprint needs |x|+|y| <= 1.414 and 1.45+1.45 is 2.9. The cheap test returns True;
    the truth is DISJOINT. This op reports BOTH, so the caller can see when the approximation would
    have lied.

    FIVE ANSWERS, because "do they overlap" is really several questions:

      DISJOINT       no shared volume and no contact
      TOUCHING       surfaces meet, no shared volume - two boxes flush against each other
      INTERSECTING   surfaces cross and volume is shared
      A_INSIDE_B     A is wholly within B, with no surface contact at all
      B_INSIDE_A     the same the other way

    CONTAINMENT IS THE CASE A SURFACE TEST CANNOT SEE. overlap() reports FACE-to-FACE intersection
    only, so a cube entirely inside another returns ZERO pairs - measured on 3.6, 4.4 and 5.0, where
    the same pair had 14 of 14 sample points inside. Testing len(overlap()) alone calls that
    DISJOINT, which is the exact opposite of the truth.

    pairCount IS NOT A CONTACT COUNT. overlap() under-reports badly on coincident geometry: two
    identical cubes at the same location return 2 pairs rather than the 36 a caller might expect.
    The boolean is sound and the number is not, so it is reported with that said rather than left to
    be misread.

    params:
      a (str), b (str)      the two objects. Both must be MESH.
      objects [a, b]        an alternative spelling of the same pair
      tolerance (float)     how far inside a point must be to count. Default 1e-5.
      maxSamples (int)      cap on containment sample points per object. Default 2000.
      evaluated (bool)      use the MODIFIER RESULT rather than the base mesh. Default true - what
                            renders and what collides is the evaluated geometry.
    """
    reject_unknown(params, _OVERLAP_KEYS, "objects_overlap")
    pair = params.get("objects")
    if pair is not None:
        if not isinstance(pair, (list, tuple)) or len(pair) != 2:
            raise MifOpError("'objects' must be exactly two object names, got %r." % (pair,))
        a_name, b_name = str(pair[0]), str(pair[1])
    else:
        a_name = take(params, "a", required=True, kind=str)
        b_name = take(params, "b", required=True, kind=str)
    if a_name == b_name:
        raise MifOpError("'%s' was given for both objects. An object always overlaps itself, so "
                         "the answer would be true and useless." % a_name)

    tol = take_float(params, "tolerance", default=1e-5)
    if tol < 0.0:
        raise MifOpError("tolerance cannot be negative, got %g." % tol)
    max_samples = take_int(params, "maxSamples", default=_DEFAULT_OVERLAP_SAMPLES)
    if max_samples < 1:
        raise MifOpError("maxSamples must be at least 1, got %d." % max_samples)
    use_eval = take_bool(params, "evaluated", default=True)

    obj_a, obj_b = get_object(a_name), get_object(b_name)
    # BOTH TYPE CHECKS BEFORE EITHER MESH READ. Interleaved, a non-MESH `b` goes unreported
    # whenever `a` has anything odd about its data - and the type check is the one guarding against
    # a class of object this op must never hand to a BVH builder.
    for obj in (obj_a, obj_b):
        if obj.type != "MESH":
            raise MifOpError("'%s' is a %s. Only meshes have a surface to intersect."
                             % (obj.name, obj.type))
    for obj in (obj_a, obj_b):
        if not obj.data.polygons:
            raise MifOpError("'%s' has no faces, so it encloses nothing and cannot overlap "
                             "anything." % obj.name)

    depsgraph = bpy.context.evaluated_depsgraph_get()
    tree_a, pts_a = _world_bvh(obj_a, depsgraph, use_eval)
    tree_b, pts_b = _world_bvh(obj_b, depsgraph, use_eval)

    # SUBSAMPLED BY STRIDE, NOT BY TRUNCATION. Taking the first N points of a mesh samples one
    # corner of it, which on a large object is a different question from the one that was asked.
    # A stride covers the whole surface and is deterministic, so two runs agree.
    def _stride(points):
        if len(points) <= max_samples:
            return points, 1
        step = (len(points) + max_samples - 1) // max_samples
        return points[::step], step

    sam_a, stride_a = _stride(pts_a)
    sam_b, stride_b = _stride(pts_b)

    pairs = tree_a.overlap(tree_b)
    a_in = sum(1 for p in sam_a if _is_inside(tree_b, p, tol))
    b_in = sum(1 for p in sam_b if _is_inside(tree_a, p, tol))

    if pairs:
        verdict = "INTERSECTING" if (a_in or b_in) else "TOUCHING"
    elif b_in == len(sam_b):
        verdict = "B_INSIDE_A"
    elif a_in == len(sam_a):
        verdict = "A_INSIDE_B"
    elif a_in or b_in:
        # NO FACE PAIRS AND YET POINTS INSIDE. A shallow intersection whose faces cross outside the
        # sampled set - reported as intersecting rather than forced into a cleaner-sounding answer.
        verdict = "INTERSECTING"
    else:
        verdict = "DISJOINT"

    # THE CHEAP TEST, REPORTED ALONGSIDE. This is the answer an AABB implementation would have
    # given, so a caller can see the disagreement rather than take it on faith that the expensive
    # path was worth taking.
    def _aabb(obj):
        corners = [obj.matrix_world @ mathutils.Vector(c) for c in obj.bound_box]
        return ([min(c[i] for c in corners) for i in range(3)],
                [max(c[i] for c in corners) for i in range(3)])

    lo_a, hi_a = _aabb(obj_a)
    lo_b, hi_b = _aabb(obj_b)
    aabb_overlap = all(lo_a[i] <= hi_b[i] and lo_b[i] <= hi_a[i] for i in range(3))
    truth = verdict != "DISJOINT"

    return {
        "ok": True,
        "a": obj_a.name,
        "b": obj_b.name,
        "overlapping": truth,
        "verdict": verdict,
        "space": "WORLD",
        "geometry": "evaluated" if use_eval else "base",
        # A BOOLEAN-GRADE SIGNAL, NOT A CONTACT COUNT - overlap() returns 2 pairs for two identical
        # coincident cubes rather than 36. Said here rather than left to be misread.
        "facePairs": len(pairs),
        "facePairsNote": ("the number of intersecting face pairs is unreliable - overlap() "
                          "under-reports badly on coincident geometry. Use it as yes/no."),
        "samplesInsideOther": {"aInB": a_in, "bInA": b_in},
        "samplesTested": {"a": len(sam_a), "b": len(sam_b), "strideA": stride_a,
                          "strideB": stride_b},
        "aabbSaysOverlap": aabb_overlap,
        # THE HEADLINE WHEN THEY DISAGREE. An AABB test is what this was being approximated with,
        # and this is the case that made it worth replacing.
        "aabbWouldHaveLied": aabb_overlap != truth,
        "note": ("the bounding boxes intersect and the GEOMETRY does not - an axis-aligned box "
                 "around a rotated object covers space the object does not occupy, which is the "
                 "false positive this op exists to remove.")
        if (aabb_overlap and not truth) else
        (("the geometry overlaps and the bounding-box test agrees, so the cheap answer would have "
          "been right here too.") if aabb_overlap and truth else None),
    }

OPS = {
    "ray_cast": op_ray_cast,
    "closest_point_on_mesh": op_closest_point,
    "face_info": op_face_info,
    "select_faces": op_select_faces,
    "bisect_plane": op_bisect_plane,
    "set_shading": op_set_shading,
    "objects_overlap": op_objects_overlap,
}
