"""Asking the geometry questions - ray casts, nearest points, and what is on which face.

WHY THESE AND WHY FIRST. This module was not chosen from a wishlist. It was chosen by counting what
real scripts actually escaped to run_python for: of 21 escapes in one day's work, 13 were RAY
CASTING and 15 were reading PER-FACE MATERIAL. Those two absences account for nearly every escape,
which makes them worth more than any number of features nobody reached for.

run_python is the arbitrary-code switch a user may well have turned off, so an addon that cannot
answer "what is at this point" or "which faces carry this material" is one that stops being usable
exactly when the work gets specific - finding a hole in a deck, locating a stairwell, selecting the
glass faces of a building.

=============================================================================
THE COORDINATE SPACE IS THE WHOLE CORRECTNESS STORY
=============================================================================
obj.ray_cast and obj.closest_point_on_mesh take and return the object's LOCAL space. A caller who
hands them world coordinates gets a miss, or worse a hit somewhere plausible and wrong, with
nothing anywhere saying so - and a moved, rotated or scaled object is the normal case, not the
exception. So this op takes WORLD coordinates, converts in, and converts back out. The space is
named in the response rather than assumed.

AND A NORMAL IS NOT A POINT. Transforming a normal by matrix_world is correct only while the scale
is uniform; under non-uniform scale it skews, and the result still looks like a unit-ish vector
pointing roughly the right way. Normals go through the INVERSE TRANSPOSE of the 3x3, which is the
one line in this file most likely to be got wrong by someone reimplementing it in a hurry.

=============================================================================
EVALUATED, NOT BASE, GEOMETRY
=============================================================================
scene.ray_cast works on the depsgraph, so it hits what is actually THERE - subdivided, displaced,
mirrored, generated by geometry nodes. obj.ray_cast works on the object's own mesh, which is the
cage. Those are different questions and both are legitimate, so the response says which one was
asked and the object form reports whether the object has modifiers that make them differ.
"""
import bpy
import mathutils

from .ops_common import MifOpError, get_object, reject_unknown, rnd, take, take_bool, take_float

_RAY_KEYS = {"origin", "direction", "target", "object", "name", "distance", "evaluated"}
# NO "name" ALIAS HERE. object is required and unambiguous, and param_reach flagged the alias
# as an accepted key no MCP tool can send. ray_cast and face_info keep theirs because both
# take the object OPTIONALLY, where a second spelling earns its place.
_NEAR_KEYS = {"object", "point", "distance"}
_FACE_KEYS = {"object", "name", "material", "slot", "indices", "limit", "withFaces",
              "evaluated"}

_DEFAULT_FACE_LIMIT = 200


def _vec(params, key, required=False, default=None):
    raw = params.get(key)
    if raw is None:
        if required:
            raise MifOpError("'%s' is required and must be [x,y,z]." % key)
        return None if default is None else mathutils.Vector(default)
    if isinstance(raw, dict):
        try:
            return mathutils.Vector((float(raw["x"]), float(raw["y"]), float(raw["z"])))
        except (KeyError, TypeError, ValueError):
            raise MifOpError("'%s' as an object needs x, y and z, got %r." % (key, raw))
    if not isinstance(raw, (list, tuple)) or len(raw) < 3:
        raise MifOpError("'%s' must be [x,y,z] or {x,y,z}, got %r." % (key, raw))
    try:
        return mathutils.Vector((float(raw[0]), float(raw[1]), float(raw[2])))
    except (TypeError, ValueError):
        raise MifOpError("'%s' must be three numbers, got %r." % (key, raw))


def _normal_to_world(obj, local_normal):
    """A normal from object space to world space.

    THE INVERSE TRANSPOSE, not matrix_world. Multiplying a normal by the object matrix is only
    correct while the scale is uniform; under non-uniform scale it SKEWS, and what comes out is
    still a plausible-looking vector pointing roughly the right way - so the error survives every
    eyeball check and shows up later as lighting or alignment that is subtly wrong.
    """
    m = obj.matrix_world.inverted_safe().transposed().to_3x3()
    return (m @ local_normal).normalized()


def op_ray_cast(params):
    """Fire a ray and report what it hits - in WORLD coordinates, both ways.

    THE SINGLE MOST-ESCAPED-TO OPERATION. Counted rather than guessed: 13 of 21 run_python escapes
    in one day were ray casts. It is what answers "what is at this point", "what is under it", "is
    anything across this edge" - the questions every layout, hard-surface and level job is built on.

    TWO FORMS, AND THEY ANSWER DIFFERENT QUESTIONS:
      no `object`   the whole scene, through the depsgraph - so it hits what is actually THERE:
                    subdivided, displaced, mirrored, generated by geometry nodes.
      `object`      that object only. Its own mesh by default, or its evaluated one with
                    evaluated:true. The difference matters the moment the object has a modifier,
                    and the response says which was used.

    COORDINATES ARE WORLD IN AND WORLD OUT. obj.ray_cast is LOCAL on both sides, and handing it
    world coordinates yields a miss or a plausible wrong hit with nothing to say so - a moved or
    rotated object being the normal case. The conversion happens here.

    params:
      origin [x,y,z]      required, world space
      direction [x,y,z]   required unless `target` is given. Need not be normalised.
      target [x,y,z]      cast TOWARDS this point instead of giving a direction
      object / name (str) restrict the cast to one object
      distance (float)    maximum range. Default unlimited.
      evaluated (bool)    object form only - cast against the modifier result. Default false.
    """
    reject_unknown(params, _RAY_KEYS, "ray_cast")
    origin = _vec(params, "origin", required=True)
    target = _vec(params, "target")
    direction = _vec(params, "direction")
    if target is not None and direction is not None:
        raise MifOpError("pass direction OR target, not both - target IS a direction, expressed "
                         "from the origin.")
    if target is None and direction is None:
        raise MifOpError("'direction' is required, or 'target' to cast towards a point.")
    if target is not None:
        direction = target - origin
    if direction.length == 0.0:
        raise MifOpError("the direction has zero length%s - a ray with no direction hits nothing."
                         % (" (target is the origin)" if target is not None else ""))
    direction = direction.normalized()

    distance = take_float(params, "distance", default=None)
    if distance is not None and distance <= 0.0:
        raise MifOpError("distance must be greater than 0, got %g." % distance)
    limit = distance if distance is not None else 1.0e38

    name = take(params, "object", "name", kind=str)
    # THE OBJECT IS VALIDATED BEFORE THE DEPSGRAPH IS ASKED FOR. evaluated_depsgraph_get()
    # forces an evaluation of the whole scene, which is real work to do on the way to
    # refusing - and this op is called in loops, where "cheap when it fails" is not a
    # nicety. Found by a check asserting the refusal rather than by reading.
    obj = None
    if name:
        obj = get_object(name)
        if obj.type != "MESH":
            raise MifOpError("'%s' is a %s. Only a MESH can be ray cast against directly; "
                             "omit 'object' to cast against the whole scene."
                             % (name, obj.type))
    depsgraph = bpy.context.evaluated_depsgraph_get()

    if obj is None:
        hit, loc, nrm, index, obj, _mat = bpy.context.scene.ray_cast(
            depsgraph, origin, direction, distance=limit)
        out = {
            "ok": True,
            "hit": bool(hit),
            "space": "WORLD",
            "against": "scene (evaluated depsgraph)",
            "origin": rnd(list(origin)),
            "direction": rnd(list(direction)),
        }
        if hit:
            out.update({
                "location": rnd(list(loc)),
                # ALREADY WORLD-SPACE. scene.ray_cast returns world coordinates and a world normal,
                # unlike the object form - so no conversion here, and doing one anyway would be the
                # mirror-image bug.
                "normal": rnd(list(nrm)),
                "faceIndex": int(index),
                "object": obj.name if obj else None,
                "distance": round((loc - origin).length, 6),
            })
        else:
            out["note"] = ("nothing was hit within %s. A scene cast uses the EVALUATED geometry, so "
                           "an object hidden from the viewport with hide_viewport is not in the "
                           "depsgraph and cannot be hit."
                           % ("%g units" % distance if distance else "any distance"))
        return out

    use_eval = take_bool(params, "evaluated", default=False)
    source = obj.evaluated_get(depsgraph) if use_eval else obj

    # WORLD IN, LOCAL FOR THE CALL. This is the conversion whose absence is the silent failure.
    inv = obj.matrix_world.inverted_safe()
    local_origin = inv @ origin
    local_dir = (inv.to_3x3() @ direction).normalized()

    hit, loc, nrm, index = source.ray_cast(local_origin, local_dir, distance=limit)
    modifiers = [m.name for m in obj.modifiers] if hasattr(obj, "modifiers") else []
    out = {
        "ok": True,
        "hit": bool(hit),
        "space": "WORLD",
        "against": "%s (%s geometry)" % (obj.name, "evaluated" if use_eval else "base"),
        "object": obj.name,
        "origin": rnd(list(origin)),
        "direction": rnd(list(direction)),
        "modifiers": modifiers,
    }
    if modifiers and not use_eval:
        out["note"] = ("'%s' has %d modifier(s) and this cast used its BASE mesh, so the surface "
                       "hit is the cage rather than what renders. Pass evaluated:true for the "
                       "modifier result." % (obj.name, len(modifiers)))
    if hit:
        world_loc = obj.matrix_world @ loc
        out.update({
            "location": rnd(list(world_loc)),
            "normal": rnd(list(_normal_to_world(obj, nrm))),
            "localLocation": rnd(list(loc)),
            "faceIndex": int(index),
            "distance": round((world_loc - origin).length, 6),
        })
    elif "note" not in out:
        out["note"] = "the ray missed '%s'." % obj.name
    return out


def op_closest_point(params):
    """The nearest point ON a mesh to a point in space - "what is under it", without a direction.

    The other half of ray_cast, and the one to reach for when there is no obvious direction to cast
    in: snapping something to a surface, measuring clearance, finding which face an object sits over.

    WORLD IN, WORLD OUT, for the same reason and with the same conversion. closest_point_on_mesh is
    local on both sides.

    params:
      object / name (str)   required, must be a MESH
      point [x,y,z]         required, world space
      distance (float)      maximum search range in LOCAL units. Default unlimited.
    """
    reject_unknown(params, _NEAR_KEYS, "closest_point_on_mesh")
    # ASSIGNED FIRST, not nested inside get_object. Every other op in this addon reads its
    # aliases into a variable, and param_reach resolves them from that form - nested, the "name"
    # alias reads as a parameter no MCP tool can send. Consistency here is not cosmetic.
    want = take(params, "object", required=True, kind=str)
    obj = get_object(want)
    if obj.type != "MESH":
        raise MifOpError("'%s' is a %s, and only a MESH has a surface to be near."
                         % (obj.name, obj.type))
    point = _vec(params, "point", required=True)
    distance = take_float(params, "distance", default=None)
    if distance is not None and distance <= 0.0:
        raise MifOpError("distance must be greater than 0, got %g." % distance)

    if not obj.data.polygons:
        raise MifOpError("'%s' has no faces, so there is no surface to be close to. It has %d "
                         "vertice(s)." % (obj.name, len(obj.data.vertices)))

    inv = obj.matrix_world.inverted_safe()
    local_point = inv @ point
    args = (local_point,) if distance is None else (local_point, distance)
    found, loc, nrm, index = obj.closest_point_on_mesh(*args)

    out = {
        "ok": True,
        "found": bool(found),
        "space": "WORLD",
        "object": obj.name,
        "point": rnd(list(point)),
    }
    if found:
        world_loc = obj.matrix_world @ loc
        out.update({
            "location": rnd(list(world_loc)),
            "normal": rnd(list(_normal_to_world(obj, nrm))),
            "localLocation": rnd(list(loc)),
            "faceIndex": int(index),
            "distance": round((world_loc - point).length, 6),
            # THE SIGN IS THE USEFUL PART. Positive means the query point is on the outside of that
            # face, negative means behind it - which is how "is this inside the mesh" gets answered
            # without a second cast.
            "signedOffset": round((point - world_loc).dot(_normal_to_world(obj, nrm)), 6),
        })
    else:
        out["note"] = ("no point within %g units of the query point." % distance if distance
                       else "closest_point_on_mesh found nothing, which for an unlimited search "
                            "means the mesh has no usable surface.")
    return out


def op_face_info(params):
    """Which faces carry which material, how many, and where they are.

    THE SECOND MOST-ESCAPED-TO QUESTION, counted rather than guessed: 15 of one day's 21 run_python
    escapes were reading per-face material. And it is a pure read/write asymmetry -
    assign_material_to_faces can WRITE that relation and nothing anywhere could read it back, so
    every "operate on just the glass faces" job had to leave the typed path entirely.

    AGGREGATE FIRST, DETAIL ON REQUEST. A production mesh has hundreds of thousands of faces, so
    returning them all is not a service; the per-slot counts, areas and bounding boxes answer most
    of the question in a fixed-size response, and withFaces asks for rows only once the caller knows
    which slot they care about.

    THE BOUNDING BOX IS REPORTED IN BOTH SPACES. Local is what the mesh data holds; world is what
    anybody positioning something against it needs, and deriving one from the other requires the
    object matrix that a caller reading this remotely does not have. Reporting only local would push
    the same transform mistake this module's ray_cast exists to prevent onto every caller.

    EMPTY SLOTS ARE REPORTED, and that is deliberate: a material slot with no faces is the state
    assign_material_to_faces leaves behind when the wrong index was used, and it is invisible from
    the material list, which shows the slot as present and assigned.

    params:
      object / name (str)     required, must be a MESH
      material (str)          only faces using this material
      slot (int)              only faces in this material slot index
      indices (list[int])     only these face indices
      limit (int)             maximum face rows returned. Default 200.
      withFaces (bool)        include per-face rows at all. Default false.
      evaluated (bool)        read the MODIFIER RESULT rather than the base mesh. Default false -
                              the base mesh is what assign_material_to_faces writes to, so it is
                              what a caller comparing against a write needs.
    """
    reject_unknown(params, _FACE_KEYS, "face_info")
    want = take(params, "object", "name", required=True, kind=str)
    obj = get_object(want)
    if obj.type != "MESH":
        raise MifOpError("'%s' is a %s and has no faces." % (obj.name, obj.type))

    # EVERY PARAMETER IS CHECKED BEFORE ANY MESH DATA IS TOUCHED. Reading material_slots, or
    # evaluating the depsgraph, on the way to refusing a bad argument combination is work done for
    # nothing - and on a heavy mesh it is a lot of it, in an op meant to be called in a loop. Only
    # the checks that NEED the mesh (does that slot exist, is that face index in range) happen
    # after. Found by checks asserting these refusals, not by reading the code.
    want_mat = take(params, "material", kind=str)
    want_slot = params.get("slot")
    indices = params.get("indices")
    if want_mat is not None and want_slot is not None:
        raise MifOpError("pass material OR slot, not both - a material can occupy more than one "
                         "slot, so the two can disagree and only one of them could win.")
    if indices is not None and not isinstance(indices, (list, tuple)):
        raise MifOpError("'indices' must be a list of face indices, got %s."
                         % type(indices).__name__)
    limit = params.get("limit")
    limit = _DEFAULT_FACE_LIMIT if limit is None else int(limit)
    if limit < 0:
        raise MifOpError("'limit' cannot be negative, got %d." % limit)
    with_faces = take_bool(params, "withFaces", default=False)

    use_eval = take_bool(params, "evaluated", default=False)
    if use_eval:
        depsgraph = bpy.context.evaluated_depsgraph_get()
        mesh = obj.evaluated_get(depsgraph).data
    else:
        mesh = obj.data

    slots = [s.material.name if s.material else None for s in obj.material_slots]
    slot_filter = None
    if want_mat is not None:
        matching = [i for i, n in enumerate(slots) if n == want_mat]
        if not matching:
            raise MifOpError("'%s' has no material slot holding '%s'. Its slots are: %s."
                             % (obj.name, want_mat,
                                ", ".join("%d=%s" % (i, n or "<empty>")
                                          for i, n in enumerate(slots)) or "<none>"))
        slot_filter = set(matching)
    elif want_slot is not None:
        try:
            want_slot = int(want_slot)
        except (TypeError, ValueError):
            raise MifOpError("'slot' must be an integer index, got %r." % (want_slot,))
        if not 0 <= want_slot < max(len(slots), 1):
            raise MifOpError("slot %d is out of range - '%s' has %d slot(s)."
                             % (want_slot, obj.name, len(slots)))
        slot_filter = {want_slot}

    index_filter = None
    if indices is not None:
        try:
            index_filter = {int(i) for i in indices}
        except (TypeError, ValueError):
            raise MifOpError("'indices' must be whole numbers.")
        highest = len(mesh.polygons) - 1
        bad = sorted(i for i in index_filter if i < 0 or i > highest)
        if bad:
            raise MifOpError("face index %s is out of range - '%s' has %d face(s), so the highest "
                             "index is %d." % (bad[0], obj.name, len(mesh.polygons), highest))

    mw = obj.matrix_world
    per_slot = {}
    rows = []
    matched = 0
    for poly in mesh.polygons:
        si = poly.material_index
        if slot_filter is not None and si not in slot_filter:
            continue
        if index_filter is not None and poly.index not in index_filter:
            continue
        matched += 1
        agg = per_slot.setdefault(si, {"faceCount": 0, "area": 0.0, "lo": None, "hi": None})
        agg["faceCount"] += 1
        agg["area"] += float(poly.area)
        for v in poly.vertices:
            co = mesh.vertices[v].co
            if agg["lo"] is None:
                agg["lo"] = [co[0], co[1], co[2]]
                agg["hi"] = [co[0], co[1], co[2]]
            else:
                for a in range(3):
                    agg["lo"][a] = min(agg["lo"][a], co[a])
                    agg["hi"][a] = max(agg["hi"][a], co[a])
        if with_faces and len(rows) < limit:
            centre = poly.center
            rows.append({
                "index": poly.index,
                "slot": si,
                "material": slots[si] if si < len(slots) else None,
                "area": round(float(poly.area), 6),
                "vertexCount": len(poly.vertices),
                "centerWorld": rnd(list(mw @ centre)),
                "normalWorld": rnd(list(_normal_to_world(obj, poly.normal))),
                "smooth": bool(poly.use_smooth),
            })

    slot_rows = []
    for si in range(max(len(slots), (max(per_slot) + 1) if per_slot else 0)):
        agg = per_slot.get(si)
        row = {
            "slot": si,
            "material": slots[si] if si < len(slots) else None,
            "faceCount": agg["faceCount"] if agg else 0,
            "area": round(agg["area"], 6) if agg else 0.0,
        }
        if agg and agg["lo"] is not None:
            lo = mathutils.Vector(agg["lo"])
            hi = mathutils.Vector(agg["hi"])
            row["bboxLocal"] = {"min": rnd(list(lo)), "max": rnd(list(hi)),
                                "size": rnd([hi[a] - lo[a] for a in range(3)])}
            # THE WORLD BOX IS BUILT FROM ALL EIGHT CORNERS, not from transforming min and max.
            # Transforming two opposite corners is correct only for an axis-aligned matrix; under
            # any rotation it produces a box that is the wrong size and, worse, plausible.
            corners = [mw @ mathutils.Vector((lo[0] if i & 1 else hi[0],
                                              lo[1] if i & 2 else hi[1],
                                              lo[2] if i & 4 else hi[2])) for i in range(8)]
            wlo = [min(c[a] for c in corners) for a in range(3)]
            whi = [max(c[a] for c in corners) for a in range(3)]
            row["bboxWorld"] = {"min": rnd(wlo), "max": rnd(whi),
                                "size": rnd([whi[a] - wlo[a] for a in range(3)])}
        slot_rows.append(row)

    empty = [r["slot"] for r in slot_rows if r["faceCount"] == 0 and r["material"]]
    out = {
        "ok": True,
        "object": obj.name,
        "geometry": "evaluated" if use_eval else "base",
        "faceCount": len(mesh.polygons),
        "facesMatched": matched,
        "materialSlots": slot_rows,
        "slotsWithNoFaces": empty,
    }
    if with_faces:
        out["faces"] = rows
        out["facesReturned"] = len(rows)
        # NO SILENT TRUNCATION. A caller who gets 200 rows out of 40000 and is not told has a
        # sample they will treat as the set.
        out["facesTruncated"] = matched > len(rows)
        if out["facesTruncated"]:
            out["truncationNote"] = ("%d face(s) matched and %d were returned - raise limit, or "
                                     "filter by material or slot." % (matched, len(rows)))
    if empty:
        out["emptySlotNote"] = ("slot(s) %s hold a material and NO faces. That is what "
                                "assign_material_to_faces leaves behind when the wrong slot index "
                                "was used, and it is invisible from the material list, which shows "
                                "the slot as present." % ", ".join(str(s) for s in empty))
    return out


OPS = {
    "ray_cast": op_ray_cast,
    "closest_point_on_mesh": op_closest_point,
    "face_info": op_face_info,
}
