// MifBridge — apply_graph_patch: many dependent graph edits as ONE call, with REAL rollback.
//
// Why this exists. Wiring one round-trip driver took ~17 exec connections, 20+ data connections and
// several pin defaults — each its own HTTP call. That is slow, expensive in tokens, and worse: when
// one operation misbehaved the blueprint was left half-wired, with dead exec branches and unresolved
// wildcards, and recovery meant reading the whole graph back to work out what had actually landed.
//
// WHY THIS DOES NOT USE THE TRANSACTION SYSTEM FOR ROLLBACK.
// RunEndpoint wraps handlers in an FScopedTransaction and calls Cancel() on failure, and Cancel
// DISCARDS THE UNDO ENTRY — IT REVERTS NOTHING (MifBridgeCommon.cpp:1055, PM-007). So "wrap 40 edits
// in a transaction and cancel" would produce exactly the partial state it was supposed to prevent,
// while looking atomic. This endpoint therefore keeps an explicit INVERSE for every operation it
// applies and replays those inverses in reverse order when something fails. That is the only way
// rollback here can be real, and it is why the op set is restricted to operations that genuinely
// have an inverse.
//
// SUPPORTED OPS — deliberately the three that dominate the cost and are exactly invertible:
//   connect_pins     inverse: restore both endpoints' prior link sets AND their prior pin defaults
//   disconnect_pin   inverse: restore every link it broke
//   set_pin_default  inverse: write the recorded previous value back
// Node CREATION is not included. It is invertible in principle (delete the node), but a created node
// is rarely the expensive part — a graph build is dominated by wiring — and quietly deleting nodes
// during a rollback is a destructive act this endpoint should not perform without its own confirm.
// Create nodes with add_* first, then wire them here in one call.
//
// ------------------------------------------------------------------------------------------------
// WHAT THE ENGINE ACTUALLY DOES ON A CONNECTION, AND WHY THIS FILE IS SHAPED AROUND IT.
// Read UEdGraphSchema::TryCreateConnection (Runtime/Engine/Private/EdGraph/EdGraphSchema.cpp) before
// changing anything here. A "connect" is not one atomic link:
//
//   1. BREAK_OTHERS_A / _B / _AB silently break whatever was already on a single-link pin. Undoing
//      only the new link would leave that pre-existing wire destroyed while reporting a clean
//      rollback — precisely the "ok:false means nothing changed" lie this endpoint exists to kill.
//      -> both endpoints' FULL prior link sets are snapshotted and restored.
//
//   2. It then calls PinConnectionListChanged on BOTH owning nodes. The UK2Node base override
//      (K2Node.cpp) calls ResetPinToAutogeneratedDefaultValue on a newly-connected INPUT pin — so
//      connecting WIPES that pin's default value. Restoring links alone would silently lose it.
//      -> both endpoints' prior defaults are snapshotted and restored too.
//
//   3. That same override can RemovePin() an orphaned pin, and UEdGraphSchema_K2::TryCreateConnection
//      guards its own PinA with IsPendingKill() — the engine itself treats the pin as possibly dead
//      after the call. A journal of raw UEdGraphPin* replayed later is therefore a use-after-free,
//      the same bug class that already crashed this editor once via ReconstructNode (see
//      docs/01_POSTMORTEMS.md, and the add_pin fix in MifBridgeNodes.cpp).
//      -> NOTHING here stores a UEdGraphPin* across operations. Pins are recorded as FPinRef
//         (node guid + pin name + direction) and re-resolved from the graph at the moment of use.
//
//   4. MAKE_WITH_CONVERSION_NODE creates a whole extra node and wires A -> [conv] -> B, and
//      MAKE_WITH_PROMOTION rewrites pin types. Neither has an inverse this endpoint can honestly
//      replay, so both are REFUSED AT PREFLIGHT rather than applied and half-undone.
// ------------------------------------------------------------------------------------------------
#include "MifBridgeHandlers.h"
#include "MifBridgeLog.h"

#include "EdGraph/EdGraph.h"
#include "EdGraph/EdGraphNode.h"
#include "EdGraph/EdGraphPin.h"
#include "EdGraphSchema_K2.h"
#include "Kismet2/BlueprintEditorUtils.h"

namespace MifBridge
{
	namespace
	{
		// STABLE PIN IDENTITY. A UEdGraphPin* is not safe to hold across a graph mutation (see the
		// header note). Node guid + pin name + direction survives reconstruction, because a
		// reconstructed node keeps its NodeGuid and recreates pins under the same names.
		struct FPinRef
		{
			FGuid NodeGuid;
			FName PinName;
			EEdGraphPinDirection Dir = EGPD_Input;
			bool bSet = false;

			FString Describe() const
			{
				return FString::Printf(TEXT("%s.%s(%s)"), *NodeGuid.ToString(EGuidFormats::DigitsWithHyphens),
					*PinName.ToString(), Dir == EGPD_Input ? TEXT("in") : TEXT("out"));
			}
		};

		UEdGraphNode* FindNodeInGraph(UEdGraph* Graph, const FGuid& Guid)
		{
			if (!Graph || !Guid.IsValid()) { return nullptr; }
			for (UEdGraphNode* N : Graph->Nodes)
			{
				if (N && N->NodeGuid == Guid) { return N; }
			}
			return nullptr;
		}

		UEdGraphNode* FindNodeInGraphByStr(UEdGraph* Graph, const FString& GuidStr)
		{
			FGuid Guid;
			if (!FGuid::Parse(GuidStr, Guid)) { return nullptr; }
			return FindNodeInGraph(Graph, Guid);
		}

		FPinRef MakeRef(UEdGraphPin* Pin)
		{
			FPinRef R;
			if (Pin && Pin->GetOwningNodeUnchecked())
			{
				R.NodeGuid = Pin->GetOwningNodeUnchecked()->NodeGuid;
				R.PinName = Pin->PinName;
				R.Dir = Pin->Direction;
				R.bSet = true;
			}
			return R;
		}

		// EXACT re-resolution: same name, same direction, no alias fallbacks. FindPin's friendly
		// aliases are right for caller-supplied spellings and wrong here — this ref was minted from a
		// real pin, so anything but an exact match means the pin is gone and we must say so.
		UEdGraphPin* ResolveRef(UEdGraph* Graph, const FPinRef& Ref)
		{
			if (!Ref.bSet) { return nullptr; }
			UEdGraphNode* Node = FindNodeInGraph(Graph, Ref.NodeGuid);
			if (!Node) { return nullptr; }
			for (UEdGraphPin* Pin : Node->Pins)
			{
				if (Pin && Pin->PinName == Ref.PinName && Pin->Direction == Ref.Dir) { return Pin; }
			}
			return nullptr;
		}

		// A pin's default value in all three of the forms the engine keeps it in.
		struct FPinDefaults
		{
			FString Value;
			// Kept as FText, NOT round-tripped through FString. FText::FromString(Text.ToString())
			// produces a NEW culture-invariant text and throws away the namespace/key, so a localized
			// pin default would come back from a "clean" rollback silently delocalized.
			FText TextValue;
			UObject* Object = nullptr;

			static FPinDefaults Capture(UEdGraphPin* Pin)
			{
				FPinDefaults D;
				if (Pin)
				{
					D.Value = Pin->DefaultValue;
					D.TextValue = Pin->DefaultTextValue;
					D.Object = Pin->DefaultObject;
				}
				return D;
			}
			void RestoreTo(UEdGraphPin* Pin) const
			{
				if (!Pin) { return; }
				Pin->DefaultValue = Value;
				Pin->DefaultTextValue = TextValue;
				Pin->DefaultObject = Object;
			}
		};

		// NODE SHAPE = every pin's name, direction and full type. This is the general defence against
		// nodes that RECONFIGURE THEMSELVES when their connections change: UK2Node_Select,
		// MakeArray/MakeMap/MakeSet, ForEachLoop, GetArrayItem and friends resolve a wildcard pin's
		// type on connect and revert it on disconnect, some via ReconstructNode(). The journal can
		// restore links and defaults, but it cannot restore a retyped pin - so instead of enumerating
		// which node classes do this (a list that would rot), compare the shape either side of the
		// operation and refuse to claim a clean rollback when it changed.
		FString NodeShape(UEdGraphNode* Node)
		{
			if (!Node) { return FString(); }
			FString Sig;
			Sig.Reserve(256);
			for (UEdGraphPin* P : Node->Pins)
			{
				if (!P) { continue; }
				Sig += P->PinName.ToString();
				Sig += TEXT("|");
				Sig += FString::FromInt(static_cast<int32>(P->Direction));
				Sig += TEXT("|");
				Sig += P->PinType.PinCategory.ToString();
				Sig += TEXT("/");
				Sig += P->PinType.PinSubCategory.ToString();
				Sig += TEXT("/");
				Sig += P->PinType.PinSubCategoryObject.IsValid()
					? P->PinType.PinSubCategoryObject->GetName() : FString();
				Sig += TEXT("/");
				Sig += FString::FromInt(static_cast<int32>(P->PinType.ContainerType));
				Sig += TEXT("/");
				Sig += P->PinType.bIsReference ? TEXT("1") : TEXT("0");
				Sig += TEXT(";");
			}
			return Sig;
		}

		// One applied operation and how to undo it. Recorded only AFTER the operation actually
		// succeeded, so a rollback never tries to undo something that never happened.
		struct FPatchUndo
		{
			enum class EKind { Connected, Disconnected, DefaultSet } Kind;

			FPinRef A;
			FPinRef B;                       // Connected: the other end
			TArray<FPinRef> PriorLinksA;
			TArray<FPinRef> PriorLinksB;
			FPinDefaults PriorDefaultsA;     // Connected wipes input defaults; DefaultSet overwrites them
			FPinDefaults PriorDefaultsB;

			// Shape of each touched node BEFORE the op, so rollback can verify the node actually came
			// back rather than assume it did.
			FString ShapeA;
			FString ShapeB;
		};

		TArray<FPinRef> RefsOf(const TArray<UEdGraphPin*>& Pins)
		{
			TArray<FPinRef> Out;
			Out.Reserve(Pins.Num());
			for (UEdGraphPin* P : Pins)
			{
				FPinRef R = MakeRef(P);
				if (R.bSet) { Out.Add(R); }
			}
			return Out;
		}

		// Put a pin back to an exact prior link set. Reciprocal links are handled by Break/MakeLinkTo.
		// Returns the number of prior links that could NOT be restored, so the caller can report an
		// incomplete rollback instead of claiming a clean one.
		int32 RestoreLinks(UEdGraph* Graph, UEdGraphPin* Pin, const TArray<FPinRef>& Prior)
		{
			if (!Pin) { return Prior.Num(); }
			// bNotifyNodes:true to MATCH THE FORWARD PATH. Apply goes through the schema, which calls
			// PinConnectionListChanged on both owning nodes; if the inverse skipped that notification
			// the two directions would not be symmetric and node-side state (wildcard resolution,
			// sibling default resets, orphan-pin cleanup) would drift out of sync with the wires.
			Pin->BreakAllPinLinks(/*bNotifyNodes*/ true);
			int32 Lost = 0;
			for (const FPinRef& Ref : Prior)
			{
				if (UEdGraphPin* Other = ResolveRef(Graph, Ref))
				{
					Pin->MakeLinkTo(Other);
					if (UEdGraphNode* ON = Other->GetOwningNodeUnchecked()) { ON->PinConnectionListChanged(Other); }
				}
				else { ++Lost; }
			}
			if (UEdGraphNode* N = Pin->GetOwningNodeUnchecked()) { N->PinConnectionListChanged(Pin); }
			return Lost;
		}

		struct FRollbackReport
		{
			int32 Undone = 0;
			int32 UnresolvedPins = 0;   // a recorded pin no longer exists — rollback is INCOMPLETE
			int32 LostLinks = 0;
			int32 ReshapedNodes = 0;    // a node's pin set/types did not come back — see NodeShape
			TArray<FString> Problems;
		};

		// Replay the journal newest-first. Reverse order matters: a later connect may depend on an
		// earlier disconnect, and undoing them out of order would restore a state that never existed.
		FRollbackReport RollBack(UEdGraph* Graph, TArray<FPatchUndo>& Journal)
		{
			FRollbackReport Rep;
			for (int32 i = Journal.Num() - 1; i >= 0; --i)
			{
				FPatchUndo& U = Journal[i];

				// Re-resolve EVERY pin at the moment of use. Never trust a pointer captured earlier.
				UEdGraphPin* PinA = ResolveRef(Graph, U.A);
				UEdGraphPin* PinB = U.B.bSet ? ResolveRef(Graph, U.B) : nullptr;

				if (!PinA || (U.B.bSet && !PinB))
				{
					++Rep.UnresolvedPins;
					Rep.Problems.Add(FString::Printf(
						TEXT("op %d: pin %s no longer exists, that operation could NOT be undone"),
						i, !PinA ? *U.A.Describe() : *U.B.Describe()));
					continue;
				}

				switch (U.Kind)
				{
				case FPatchUndo::EKind::Connected:
					// Restore BOTH endpoints' links AND their defaults — connecting wipes the default
					// on a newly-connected input pin (UK2Node::PinConnectionListChanged).
					Rep.LostLinks += RestoreLinks(Graph, PinA, U.PriorLinksA);
					Rep.LostLinks += RestoreLinks(Graph, PinB, U.PriorLinksB);
					U.PriorDefaultsA.RestoreTo(PinA);
					U.PriorDefaultsB.RestoreTo(PinB);
					++Rep.Undone;
					break;

				case FPatchUndo::EKind::Disconnected:
					Rep.LostLinks += RestoreLinks(Graph, PinA, U.PriorLinksA);
					++Rep.Undone;
					break;

				case FPatchUndo::EKind::DefaultSet:
					U.PriorDefaultsA.RestoreTo(PinA);
					++Rep.Undone;
					break;
				}

				// VERIFY, do not assume. A wildcard pin retyped by the forward connect may not revert,
				// and the difference between "restored" and "looks restored" is the whole value of this
				// endpoint. Re-resolve the owning nodes first: restoring links can itself reconstruct.
				auto CheckShape = [&](const FPinRef& Ref, const FString& Expected, const TCHAR* Which)
				{
					if (!Ref.bSet || Expected.IsEmpty()) { return; }
					UEdGraphNode* Node = FindNodeInGraph(Graph, Ref.NodeGuid);
					const FString Now = NodeShape(Node);
					if (Now != Expected)
					{
						++Rep.ReshapedNodes;
						Rep.Problems.Add(FString::Printf(
							TEXT("op %d: node %s (%s) did not return to its previous pin shape - a pin type ")
							TEXT("resolved by this patch (wildcard/container) has NOT been reverted. The wires are ")
							TEXT("back but the node is not."),
							i, *Ref.NodeGuid.ToString(EGuidFormats::DigitsWithHyphens), Which));
					}
				};
				CheckShape(U.A, U.ShapeA, TEXT("A"));
				CheckShape(U.B, U.ShapeB, TEXT("B"));
			}
			return Rep;
		}

		// The set of pins currently feeding this pin, as stable refs, sorted for comparison.
		TArray<FPinRef> SourcesOf(UEdGraphPin* Pin)
		{
			TArray<FPinRef> Out;
			if (!Pin) { return Out; }
			for (UEdGraphPin* L : Pin->LinkedTo)
			{
				FPinRef R = MakeRef(L);
				if (R.bSet) { Out.Add(R); }
			}
			return Out;
		}

		FString DescribeRefs(const TArray<FPinRef>& Refs)
		{
			TArray<FString> Parts;
			for (const FPinRef& R : Refs) { Parts.Add(R.Describe()); }
			Parts.Sort();
			return FString::Join(Parts, TEXT(", "));
		}

		TSharedPtr<FJsonValue> RefsToJson(const TArray<FPinRef>& Refs)
		{
			TArray<TSharedPtr<FJsonValue>> Arr;
			for (const FPinRef& R : Refs)
			{
				TSharedRef<FJsonObject> J = MakeShared<FJsonObject>();
				J->SetStringField(TEXT("node"), R.NodeGuid.ToString(EGuidFormats::Digits));
				J->SetStringField(TEXT("pin"), R.PinName.ToString());
				Arr.Add(MakeShared<FJsonValueObject>(J));
			}
			return MakeShared<FJsonValueArray>(Arr);
		}

		bool RefEquals(const FPinRef& A, const FPinRef& B)
		{
			return A.bSet && B.bSet && A.NodeGuid == B.NodeGuid && A.PinName == B.PinName && A.Dir == B.Dir;
		}

		// EXEC INPUTS ARE LEGITIMATELY MULTI-SOURCE. Several exec outputs converging on one input is
		// ordinary fan-in, and the engine never auto-breaks it
		// (bBreakExistingDueToDataInput = !IsExecPin(*InputPin) && ...). Any "one source per input"
		// policy must therefore skip exec pins or it would silently destroy valid graphs.
		bool IsSingleSourceInput(UEdGraphPin* Pin)
		{
			return Pin
				&& Pin->Direction == EGPD_Input
				&& Pin->PinType.PinCategory != UEdGraphSchema_K2::PC_Exec;
		}

		// Which CanCreateConnection verdicts this endpoint is willing to apply. MAKE_WITH_CONVERSION_NODE
		// and MAKE_WITH_PROMOTION are deliberately NOT here: they create nodes / rewrite pin types, and
		// an inverse journal cannot honestly undo either. Refusing at preflight beats applying something
		// we would then have to lie about rolling back.
		bool IsInvertibleResponse(ECanCreateConnectionResponse R)
		{
			return R == CONNECT_RESPONSE_MAKE
				|| R == CONNECT_RESPONSE_BREAK_OTHERS_A
				|| R == CONNECT_RESPONSE_BREAK_OTHERS_B
				|| R == CONNECT_RESPONSE_BREAK_OTHERS_AB;
		}
	}

	// --- apply_graph_patch --------------------------------------------------
	//   in:  { graphId, operations:[...], dryRun?, stopOnFirstError?, allowPartial? }
	//   out: { applied, failed, rolledBack, results:[...], dryRun }
	//
	// operations[] entries:
	//   { op:"connect_pins",    srcNode, srcPin, dstNode, dstPin }
	//   { op:"disconnect_pin",  node, pin, direction? }   direction only when the name is ambiguous
	//   { op:"set_pin_default", node, pin, value }
	//
	// Every node is addressed by guid WITHIN graphId — no global guid search, so the duplicate-guid
	// ambiguity that bites get_node cannot occur here at all.
	void H_apply_graph_patch(const TSharedRef<FJsonObject>& In, const TSharedRef<FJsonObject>& Out)
	{
		if (RejectUnknownParams(In, Out,
			{ TEXT("graphId"), TEXT("operations"), TEXT("ops"), TEXT("dryRun"),
			  TEXT("stopOnFirstError"), TEXT("allowPartial") },
			TEXT("graphId, operations (alias: ops) - array of {op:connect_pins|disconnect_pin|set_pin_default, ...}, "
				 "dryRun (default false; resolve and validate everything, mutate nothing), "
				 "stopOnFirstError (default true), allowPartial (default false; when false a failure rolls back everything already applied)"),
			{ { TEXT("blueprintId"), TEXT("pass graphId - a patch applies to ONE graph, and node guids are resolved inside it") },
			  { TEXT("compileAfter"), TEXT("not offered here: compiling inside a multi-edit transaction is the reinstancing crash this codebase guards against. Call compile afterwards.") },
			  { TEXT("addNode"), TEXT("node creation is not a patch op - create nodes with add_* first, then wire them here. See the file header for why.") } }))
		{
			return;
		}

		UBlueprint* Blueprint = nullptr;
		UEdGraph* Graph = ResolveGraphField(In, Out, Blueprint);
		if (!Graph) { return; }

		// THE GRAPH'S OWN SCHEMA, not a hardcoded K2(). An AnimGraph is driven by UAnimationGraphSchema
		// and a state machine by UAnimationStateMachineSchema; both derive from UEdGraphSchema_K2 and
		// both OVERRIDE CanCreateConnection. Asking the K2 schema about an anim pin gets a verdict from
		// the wrong rulebook - which, for an endpoint whose entire contract is "the schema approved
		// this", is exactly the wrong place to guess.
		const UEdGraphSchema* Schema = Graph->GetSchema();
		if (!Schema) { Fail(Out, TEXT("graph has no schema")); return; }

		const TArray<TSharedPtr<FJsonValue>>* Ops = nullptr;
		if ((!JArray(In, TEXT("operations"), Ops) || !Ops)
			&& (!JArray(In, TEXT("ops"), Ops) || !Ops))
		{
			Fail(Out, TEXT("operations[] is required (alias: ops)"));
			return;
		}
		if (Ops->Num() == 0) { Fail(Out, TEXT("operations[] is empty")); return; }

		const bool bDryRun = JBool(In, TEXT("dryRun"), false);
		const bool bAllowPartial = JBool(In, TEXT("allowPartial"), false);
		// allowPartial is the remedy the preflight refusal MESSAGE tells the caller to reach for
		// ("apply the ones that resolve"). With stopOnFirstError still defaulting true it applied
		// nothing at all, because the first preflight-failed op broke the loop before any good op ran -
		// advice the endpoint itself gave, that the endpoint itself then ignored. So when the caller
		// asks for partial work and does not explicitly demand stop-on-first, keep going.
		const bool bStopOnFirst = JBool(In, TEXT("stopOnFirstError"), !bAllowPartial);

		// ---------------------------------------------------------------- PREFLIGHT
		// Resolve and validate EVERY operation before mutating anything. Most of the pain reported
		// here was a bad op discovered halfway through a 40-op build; finding it now costs nothing and
		// leaves the graph untouched.
		//
		// Note what is stored: FPinRef, never UEdGraphPin*. Preflight runs against the graph as it is
		// NOW, but by the time op N applies, ops 0..N-1 have mutated it — and a mutation can reconstruct
		// a node and free its pins. Re-resolving at apply time is what makes that safe.
		// What to do when the destination input ALREADY has a source.
		enum class EExistingPolicy { Replace, Preserve, Reject };

		struct FResolved
		{
			FString Op;
			FPinRef A;
			FPinRef B;
			FString Value;
			FString Error;
			EExistingPolicy Policy = EExistingPolicy::Replace;
			TArray<FPinRef> DstSourcesAtPreflight;
		};
		TArray<FResolved> Plan;
		Plan.Reserve(Ops->Num());
		int32 PreflightErrors = 0;

		for (int32 i = 0; i < Ops->Num(); ++i)
		{
			FResolved R;
			const TSharedPtr<FJsonObject>* ObjPtr = nullptr;
			if (!(*Ops)[i].IsValid() || !(*Ops)[i]->TryGetObject(ObjPtr) || !ObjPtr)
			{
				R.Error = TEXT("not an object");
				++PreflightErrors; Plan.Add(R); continue;
			}
			const TSharedRef<FJsonObject> O = ObjPtr->ToSharedRef();
			R.Op = JStr(O, TEXT("op")).ToLower();

			// PER-OPERATION KEY GUARD. RejectUnknownParams only sees the TOP level, so without this a
			// misspelled key inside an operation object ("srcpin_", "toNode") would be silently dropped
			// and the op would fail with a confusing "pin not found" - or worse, resolve to something
			// else. Silent parameter ignore is the most damaging bug class in this bridge; it does not
			// get a pass just because the parameter is nested one level down.
			{
				// Check the OP NAME FIRST. When it was checked last, a typo'd op ("connect_pin") fell
				// through with an allowed-key list of just {"op"}, so every other key looked unknown and
				// the caller was told about "unknown key(s) srcNode, srcPin..." instead of the actual
				// problem, which is the op name.
				if (R.Op != TEXT("connect_pins") && R.Op != TEXT("disconnect_pin") && R.Op != TEXT("set_pin_default"))
				{
					R.Error = FString::Printf(
						TEXT("unknown op '%s' - supported: connect_pins, disconnect_pin, set_pin_default"),
						*R.Op);
					++PreflightErrors; Plan.Add(R); continue;
				}

				TArray<FString> Allowed;
				Allowed.Add(TEXT("op"));
				if (R.Op == TEXT("connect_pins"))
				{
					for (const TCHAR* K : { TEXT("srcnode"), TEXT("src"), TEXT("srcpin"), TEXT("sourcepin"),
											TEXT("dstnode"), TEXT("dst"), TEXT("dstpin"), TEXT("destpin"),
											TEXT("existinglinkpolicy"), TEXT("replaceexisting") })
					{ Allowed.Add(K); }
				}
				else if (R.Op == TEXT("disconnect_pin"))
				{
					for (const TCHAR* K : { TEXT("node"), TEXT("nodeguid"), TEXT("pin"), TEXT("direction") })
					{ Allowed.Add(K); }
				}
				else if (R.Op == TEXT("set_pin_default"))
				{
					for (const TCHAR* K : { TEXT("node"), TEXT("nodeguid"), TEXT("pin"),
											TEXT("value"), TEXT("default"), TEXT("defaultvalue") })
					{ Allowed.Add(K); }
				}
				TArray<FString> Unknown;
				for (const auto& KV : O->Values)
				{
					if (!Allowed.Contains(KV.Key.ToLower())) { Unknown.Add(KV.Key); }
				}
				if (Unknown.Num() > 0)
				{
					R.Error = FString::Printf(
						TEXT("unknown key(s) in this operation: %s - they would have been IGNORED, so the op is refused instead"),
						*FString::Join(Unknown, TEXT(", ")));
					++PreflightErrors; Plan.Add(R); continue;
				}
			}

			if (R.Op == TEXT("connect_pins"))
			{
				UEdGraphNode* SrcNode = FindNodeInGraphByStr(Graph, JStrAny(O, { TEXT("srcNode"), TEXT("src") }));
				UEdGraphNode* DstNode = FindNodeInGraphByStr(Graph, JStrAny(O, { TEXT("dstNode"), TEXT("dst") }));
				if (!SrcNode || !DstNode)
				{
					R.Error = FString::Printf(TEXT("%s not found in this graph"), SrcNode ? TEXT("dstNode") : TEXT("srcNode"));
					++PreflightErrors; Plan.Add(R); continue;
				}
				UEdGraphPin* SrcPin = FindPin(SrcNode, JStrAny(O, { TEXT("srcPin"), TEXT("sourcePin") }), EGPD_Output, true);
				UEdGraphPin* DstPin = FindPin(DstNode, JStrAny(O, { TEXT("dstPin"), TEXT("destPin") }), EGPD_Input, true);
				if (!SrcPin || !DstPin)
				{
					R.Error = FString::Printf(TEXT("%s pin not found"), SrcPin ? TEXT("dst") : TEXT("src"));
					++PreflightErrors; Plan.Add(R); continue;
				}
				R.A = MakeRef(SrcPin);
				R.B = MakeRef(DstPin);
				R.DstSourcesAtPreflight = SourcesOf(DstPin);

				// existingLinkPolicy. Default REPLACE, because "connect X to Y" in a rewire means Y is
				// fed by X - and leaving it to the schema made the result depend on the callee's
				// signature (impure + no return value => the self pin appends instead of replacing),
				// which is not something a caller can reasonably predict per-operation.
				{
					FString Pol = JStr(O, TEXT("existingLinkPolicy")).ToLower();
					if (Pol.IsEmpty() && O->HasField(TEXT("replaceExisting")))
					{
						Pol = JBool(O, TEXT("replaceExisting"), true) ? TEXT("replace") : TEXT("preserve");
					}
					if (Pol.IsEmpty() || Pol == TEXT("replace")) { R.Policy = EExistingPolicy::Replace; }
					else if (Pol == TEXT("preserve"))            { R.Policy = EExistingPolicy::Preserve; }
					else if (Pol == TEXT("reject"))              { R.Policy = EExistingPolicy::Reject; }
					else
					{
						R.Error = FString::Printf(
							TEXT("existingLinkPolicy '%s' is not replace, preserve or reject"), *Pol);
						++PreflightErrors; Plan.Add(R); continue;
					}
				}

				// REJECT is decided here, before anything is mutated, and names what is in the way.
				if (R.Policy == EExistingPolicy::Reject
					&& IsSingleSourceInput(DstPin) && R.DstSourcesAtPreflight.Num() > 0)
				{
					R.Error = FString::Printf(
						TEXT("destination is already fed by %s and existingLinkPolicy is 'reject' - pass 'replace' to take it over, or 'preserve' to add alongside"),
						*DescribeRefs(R.DstSourcesAtPreflight));
					++PreflightErrors; Plan.Add(R); continue;
				}

				// Ask the schema NOW whether this connection is legal, and whether it is a KIND of
				// connection this endpoint can undo. This is the check that turns a mid-build surprise
				// into a preflight line.
				const FPinConnectionResponse Resp = Schema->CanCreateConnection(SrcPin, DstPin);
				if (Resp.Response == CONNECT_RESPONSE_DISALLOW)
				{
					R.Error = FString::Printf(TEXT("schema disallows: %s"), *Resp.Message.ToString());
					++PreflightErrors;
				}
				else if (!IsInvertibleResponse(Resp.Response))
				{
					// Refused ON PURPOSE, and the message says exactly why rather than just "no".
					R.Error = FString::Printf(
						TEXT("this connection needs %s, which apply_graph_patch cannot undo (%s) - so it is refused rather than applied with a rollback that would lie. Use connect_pins outside the patch, or insert the conversion explicitly and wire both halves here."),
						Resp.Response == CONNECT_RESPONSE_MAKE_WITH_CONVERSION_NODE
							? TEXT("an automatic CONVERSION NODE") : TEXT("a pin-type PROMOTION"),
						Resp.Response == CONNECT_RESPONSE_MAKE_WITH_CONVERSION_NODE
							? TEXT("undoing it would leave the conversion node orphaned in the graph")
							: TEXT("undoing it would not restore the original pin types"));
					++PreflightErrors;
				}
			}
			else if (R.Op == TEXT("disconnect_pin"))
			{
				UEdGraphNode* Node = FindNodeInGraphByStr(Graph, JStrAny(O, { TEXT("node"), TEXT("nodeGuid") }));
				if (!Node) { R.Error = TEXT("node not found in this graph"); ++PreflightErrors; Plan.Add(R); continue; }

				// A node CAN carry an input and an output of the same name. Without direction the
				// first match wins, which is a coin flip the caller never sees - so let them say, and
				// say so back when they did not and it was ambiguous.
				const FString PinName = JStr(O, TEXT("pin"));
				const FString Dir = JStr(O, TEXT("direction")).ToLower();
				UEdGraphPin* Pin = nullptr;
				if (Dir == TEXT("input") || Dir == TEXT("in"))
				{
					Pin = FindPin(Node, PinName, EGPD_Input, true);
					if (!Pin) { R.Error = TEXT("no INPUT pin of that name"); ++PreflightErrors; }
				}
				else if (Dir == TEXT("output") || Dir == TEXT("out"))
				{
					Pin = FindPin(Node, PinName, EGPD_Output, true);
					if (!Pin) { R.Error = TEXT("no OUTPUT pin of that name"); ++PreflightErrors; }
				}
				else if (!Dir.IsEmpty())
				{
					R.Error = FString::Printf(TEXT("direction '%s' is not input or output"), *Dir);
					++PreflightErrors;
				}
				else
				{
					UEdGraphPin* AsIn = FindPin(Node, PinName, EGPD_Input, true);
					UEdGraphPin* AsOut = FindPin(Node, PinName, EGPD_Output, true);
					if (AsIn && AsOut)
					{
						R.Error = FString::Printf(
							TEXT("'%s' names BOTH an input and an output pin on this node - pass direction:\"input\" or \"output\" to say which to disconnect"),
							*PinName);
						++PreflightErrors;
					}
					else
					{
						Pin = AsIn ? AsIn : AsOut;
						if (!Pin) { R.Error = TEXT("pin not found"); ++PreflightErrors; }
					}
				}
				R.A = MakeRef(Pin);
			}
			else if (R.Op == TEXT("set_pin_default"))
			{
				UEdGraphNode* Node = FindNodeInGraphByStr(Graph, JStrAny(O, { TEXT("node"), TEXT("nodeGuid") }));
				if (!Node) { R.Error = TEXT("node not found in this graph"); ++PreflightErrors; Plan.Add(R); continue; }
				// bRequireDir TRUE: only an INPUT pin carries a literal default. With it false, a name
				// that matches only an output pin resolved to that output, the write went nowhere, and
				// the op still reported ok - a silent no-op dressed as success.
				UEdGraphPin* Pin = FindPin(Node, JStr(O, TEXT("pin")), EGPD_Input, true);
				R.Value = JStrAny(O, { TEXT("value"), TEXT("default"), TEXT("defaultValue") });
				if (!Pin)
				{
					R.Error = FindPin(Node, JStr(O, TEXT("pin")), EGPD_Output, true)
						? TEXT("that pin is an OUTPUT - only input pins carry a literal default value")
						: TEXT("pin not found");
					++PreflightErrors;
				}
				R.A = MakeRef(Pin);
			}
			// no trailing else: an unrecognised op was already rejected by the op-name check above.
			Plan.Add(R);
		}

		TArray<TSharedPtr<FJsonValue>> Results;
		auto Emit = [&Results](int32 Index, const FString& Op, bool bOk, const FString& Detail)
			-> TSharedRef<FJsonObject>
		{
			TSharedRef<FJsonObject> J = MakeShared<FJsonObject>();
			J->SetNumberField(TEXT("index"), Index);
			J->SetStringField(TEXT("op"), Op);
			J->SetBoolField(TEXT("ok"), bOk);
			if (!Detail.IsEmpty()) { J->SetStringField(bOk ? TEXT("detail") : TEXT("error"), Detail); }
			Results.Add(MakeShared<FJsonValueObject>(J));
			return J;   // so a connect op can attach its before/after source sets
		};

		if (bDryRun || (PreflightErrors > 0 && !bAllowPartial))
		{
			for (int32 i = 0; i < Plan.Num(); ++i)
			{
				const FResolved& Pl = Plan[i];
				FString Detail = TEXT("would apply");
				if (Pl.Error.IsEmpty() && Pl.Op == TEXT("connect_pins") && Pl.DstSourcesAtPreflight.Num() > 0)
				{
					// The reported case: a dry run that said "would apply" for a destination that was
					// ALREADY fed by something else, and never mentioned it. Say what will happen to
					// the incumbent link, since that is the part a rewire actually cares about.
					Detail = FString::Printf(
						TEXT("would apply - destination is ALREADY fed by %s; policy '%s' will %s"),
						*DescribeRefs(Pl.DstSourcesAtPreflight),
						Pl.Policy == EExistingPolicy::Replace ? TEXT("replace")
							: (Pl.Policy == EExistingPolicy::Preserve ? TEXT("preserve") : TEXT("reject")),
						Pl.Policy == EExistingPolicy::Replace
							? TEXT("REMOVE the existing link(s) so the new source is the only one")
							: TEXT("KEEP them, leaving the destination with more than one source"));
				}
				Emit(i, Pl.Op, Pl.Error.IsEmpty(), Pl.Error.IsEmpty() ? Detail : Pl.Error);
			}
			Out->SetBoolField(TEXT("dryRun"), bDryRun);
			Out->SetNumberField(TEXT("operations"), Plan.Num());
			Out->SetNumberField(TEXT("preflightErrors"), PreflightErrors);
			Out->SetNumberField(TEXT("applied"), 0);
			Out->SetArrayField(TEXT("results"), Results);
			if (!bDryRun && PreflightErrors > 0)
			{
				// Refused BEFORE touching the graph. This is the whole point: the caller gets the same
				// diagnosis they would have got 20 operations in, with nothing to clean up.
				Fail(Out, FString::Printf(
					TEXT("%d of %d operations failed preflight - NOTHING WAS APPLIED, the graph is untouched. Fix them, or pass allowPartial:true to apply the ones that resolve."),
					PreflightErrors, Plan.Num()));
			}
			else if (bDryRun)
			{
				Out->SetStringField(TEXT("note"), PreflightErrors == 0
					? TEXT("every operation resolved and the schema accepted each connection; nothing was mutated")
					: TEXT("some operations would fail; nothing was mutated"));
			}
			return;
		}

		// ---------------------------------------------------------------- APPLY
		Blueprint->Modify();
		Graph->Modify();

		TArray<FPatchUndo> Journal;
		int32 Applied = 0, Failed = 0;
		FString FirstError;

		for (int32 i = 0; i < Plan.Num(); ++i)
		{
			FResolved& R = Plan[i];
			if (!R.Error.IsEmpty()) { ++Failed; Emit(i, R.Op, false, R.Error); if (bStopOnFirst) { break; } continue; }

			// RE-RESOLVE. Preflight's pointers are from before any mutation; an earlier op in this same
			// patch may have reconstructed the node and freed them.
			UEdGraphPin* PinA = ResolveRef(Graph, R.A);
			UEdGraphPin* PinB = R.B.bSet ? ResolveRef(Graph, R.B) : nullptr;
			if (!PinA || (R.B.bSet && !PinB))
			{
				++Failed;
				const FString Why = FString::Printf(
					TEXT("pin %s no longer exists - an earlier operation in this patch changed the node's pins"),
					!PinA ? *R.A.Describe() : *R.B.Describe());
				if (FirstError.IsEmpty()) { FirstError = FString::Printf(TEXT("op %d (%s): %s"), i, *R.Op, *Why); }
				Emit(i, R.Op, false, Why);
				if (bStopOnFirst) { break; }
				continue;
			}

			bool bOk = false;
			FString Detail;

			if (R.Op == TEXT("connect_pins"))
			{
				// RE-ASK THE SCHEMA, NOW. Preflight's verdict was formed against the pre-patch graph;
				// TryCreateConnection asks again at this moment, and an earlier op in THIS patch can
				// have changed the answer - a MAKE can become MAKE_WITH_CONVERSION_NODE once a wildcard
				// resolves. Preflight-only gating let that through, applied it, and then "rolled back"
				// by breaking two wires while the auto-created conversion node stayed behind, orphaned,
				// under a rollbackComplete:true. Checking here closes the window.
				const FPinConnectionResponse Now = Schema->CanCreateConnection(PinA, PinB);
				if (!IsInvertibleResponse(Now.Response))
				{
					++Failed;
					const FString Why = Now.Response == CONNECT_RESPONSE_DISALLOW
						? FString::Printf(TEXT("the schema now refuses this connection (%s) - an earlier operation in this patch changed the graph"), *Now.Message.ToString())
						: TEXT("this connection now requires a conversion node or a type promotion, which cannot be undone - an earlier operation in this patch changed the graph. Nothing was applied for this op.");
					if (FirstError.IsEmpty()) { FirstError = FString::Printf(TEXT("op %d (%s): %s"), i, *R.Op, *Why); }
					Emit(i, R.Op, false, Why);
					if (bStopOnFirst) { break; }
					continue;
				}

				PinA->GetOwningNode()->Modify();
				PinB->GetOwningNode()->Modify();

				// Snapshot BEFORE anything - afterwards the broken links are gone and the input pin's
				// default has already been wiped by PinConnectionListChanged. This snapshot also covers
				// the explicit break below, so rollback restores links this endpoint removed itself.
				FPatchUndo U;
				U.Kind = FPatchUndo::EKind::Connected;
				U.A = R.A; U.B = R.B;
				U.PriorLinksA = RefsOf(PinA->LinkedTo);
				U.PriorLinksB = RefsOf(PinB->LinkedTo);
				U.PriorDefaultsA = FPinDefaults::Capture(PinA);
				U.PriorDefaultsB = FPinDefaults::Capture(PinB);
				U.ShapeA = NodeShape(PinA->GetOwningNodeUnchecked());
				U.ShapeB = NodeShape(PinB->GetOwningNodeUnchecked());

				const TArray<FPinRef> SourcesBefore = SourcesOf(PinB);

				// EXPLICIT REPLACE. Left to the schema, whether the incumbent link survives depends on
				// the CALLEE'S SIGNATURE: a self pin on an impure, no-return, non-latent function is a
				// legal multi-target pin, so the schema APPENDS instead of breaking
				// (EdGraphSchema_K2.cpp:2112 bMultipleSelfException). That produced a rewire where
				// 4 of 12 destinations replaced and 8 kept both sources, all reported ok. Breaking here
				// makes the outcome depend on the caller's stated intent instead.
				// Exec inputs are excluded - exec fan-in is legal and must not be torn down.
				bool bBrokeForReplace = false;
				if (R.Policy == EExistingPolicy::Replace && IsSingleSourceInput(PinB))
				{
					for (const FPinRef& Existing : SourcesBefore)
					{
						if (RefEquals(Existing, R.A)) { continue; }   // already the requested source
						if (UEdGraphPin* Other = ResolveRef(Graph, Existing))
						{
							PinB->BreakLinkTo(Other);
							if (UEdGraphNode* ON = Other->GetOwningNodeUnchecked()) { ON->PinConnectionListChanged(Other); }
							bBrokeForReplace = true;
						}
					}
					if (bBrokeForReplace) { PinB->GetOwningNode()->PinConnectionListChanged(PinB); }
					// Breaking can reconstruct the node; re-resolve before connecting.
					PinA = ResolveRef(Graph, R.A);
					PinB = ResolveRef(Graph, R.B);
					if (!PinA || !PinB)
					{
						++Failed;
						const FString Why = TEXT("clearing the destination's existing link reconstructed the node and the pin is gone");
						if (FirstError.IsEmpty()) { FirstError = FString::Printf(TEXT("op %d (%s): %s"), i, *R.Op, *Why); }
						Journal.Add(U);          // the break DID happen - it must be rollback-able
						Emit(i, R.Op, false, Why);
						if (bStopOnFirst) { break; }
						continue;
					}
				}

				bOk = Schema->TryCreateConnection(PinA, PinB);
				if (bOk)
				{
					Journal.Add(U);

					// VERIFY THE POSTCONDITION. "The requested link exists" is not the same as "the
					// destination ends up how the caller asked", and reporting the first as success is
					// exactly what hid this bug. Re-resolve: the connect may have reconstructed a node.
					UEdGraphPin* NowB = ResolveRef(Graph, R.B);
					const TArray<FPinRef> SourcesAfter = SourcesOf(NowB);

					TArray<FPinRef> Foreign;
					for (const FPinRef& Src : SourcesAfter)
					{
						if (!RefEquals(Src, R.A)) { Foreign.Add(Src); }
					}
					const bool bIsSingle = IsSingleSourceInput(NowB);

					if (R.Policy == EExistingPolicy::Replace && bIsSingle && Foreign.Num() > 0)
					{
						// Asked to take the pin over and did not. Fail rather than report success.
						bOk = false;
						Detail = FString::Printf(
							TEXT("connected, but the destination is STILL fed by %s. existingLinkPolicy 'replace' could not clear it, so this op is reported failed rather than as a successful rewire."),
							*DescribeRefs(Foreign));
					}
					else
					{
						Detail = FString::Printf(TEXT("%s -> %s"), *R.A.PinName.ToString(), *R.B.PinName.ToString());
						if (bBrokeForReplace)
						{
							Detail += FString::Printf(TEXT(" (REPLACED %s)"), *DescribeRefs(SourcesBefore));
						}
						else if (Foreign.Num() > 0)
						{
							// preserve, or a legitimately multi-source pin such as an exec input.
							Detail += FString::Printf(
								TEXT(" (APPENDED - destination now has %d sources, also fed by %s)"),
								SourcesAfter.Num(), *DescribeRefs(Foreign));
						}
						TSharedRef<FJsonObject> Row = Emit(i, R.Op, true, Detail);
						Row->SetBoolField(TEXT("destinationWasOccupied"), SourcesBefore.Num() > 0);
						Row->SetBoolField(TEXT("replacedExisting"), bBrokeForReplace);
						Row->SetBoolField(TEXT("appendedToExisting"), !bBrokeForReplace && Foreign.Num() > 0);
						Row->SetField(TEXT("sourcesBefore"), RefsToJson(SourcesBefore));
						Row->SetField(TEXT("sourcesAfter"), RefsToJson(SourcesAfter));
						++Applied;
						continue;   // row already emitted
					}
				}
				else
				{
					Detail = TEXT("TryCreateConnection refused it even though preflight passed - an earlier operation in this patch changed the graph");
				}
			}
			else if (R.Op == TEXT("disconnect_pin"))
			{
				PinA->GetOwningNode()->Modify();
				FPatchUndo U;
				U.Kind = FPatchUndo::EKind::Disconnected;
				U.A = R.A;
				U.PriorLinksA = RefsOf(PinA->LinkedTo);   // copy BEFORE breaking, or there is nothing to restore
				U.ShapeA = NodeShape(PinA->GetOwningNodeUnchecked());
				const int32 Broke = PinA->LinkedTo.Num();

				// Match every other disconnect in this plugin: notify the owning nodes. BreakAllPinLinks
				// defaults bNotifyNodes to FALSE, which would silently diverge from the standalone
				// disconnect_pin endpoint (MifBridgeNodes.cpp:1953) and skip orphan-pin cleanup.
				Schema->BreakPinLinks(*PinA, /*bSendsNodeNotification*/ true);

				Journal.Add(U);
				bOk = true;
				Detail = FString::Printf(TEXT("broke %d link(s)"), Broke);
			}
			else // set_pin_default
			{
				PinA->GetOwningNode()->Modify();
				FPatchUndo U;
				U.Kind = FPatchUndo::EKind::DefaultSet;
				U.A = R.A;
				U.PriorDefaultsA = FPinDefaults::Capture(PinA);
				// A default can reconfigure a node too (an enum/class literal that drives which pins
				// exist), so this op is shape-checked on rollback like the others.
				U.ShapeA = NodeShape(PinA->GetOwningNodeUnchecked());

				FString Before, After, Err; bool bChanged = false;
				bOk = SetPinDefaultChecked(PinA, R.Value, Before, After, bChanged, Err);
				if (bOk) { Journal.Add(U); Detail = After; }
				else     { Detail = Err; }
			}

			if (bOk) { ++Applied; Emit(i, R.Op, true, Detail); }
			else
			{
				++Failed;
				if (FirstError.IsEmpty()) { FirstError = FString::Printf(TEXT("op %d (%s): %s"), i, *R.Op, *Detail); }
				Emit(i, R.Op, false, Detail);
				if (bStopOnFirst) { break; }
			}
		}

		FRollbackReport Rep;
		const bool bRollingBack = (Failed > 0 && !bAllowPartial);
		if (bRollingBack)
		{
			Rep = RollBack(Graph, Journal);
			Applied = 0;

			// results[] said ok:true for these while applied says 0. Both cannot be true, and a caller
			// scanning the per-op array would conclude the work landed. Restamp them as undone.
			for (const TSharedPtr<FJsonValue>& V : Results)
			{
				const TSharedPtr<FJsonObject>* Row = nullptr;
				if (V.IsValid() && V->TryGetObject(Row) && Row && (*Row)->GetBoolField(TEXT("ok")))
				{
					(*Row)->SetBoolField(TEXT("ok"), false);
					(*Row)->SetBoolField(TEXT("rolledBack"), true);
					(*Row)->SetStringField(TEXT("error"),
						TEXT("applied, then UNDONE because a later operation in this patch failed"));
				}
			}
		}

		FBlueprintEditorUtils::MarkBlueprintAsModified(Blueprint);

		// stopOnFirstError leaves the tail of the plan untouched. Without a count, results[] simply
		// ends and a caller cannot tell "the rest passed" from "the rest never ran".
		const int32 Skipped = FMath::Max(0, Plan.Num() - Results.Num());
		Out->SetNumberField(TEXT("operations"), Plan.Num());
		Out->SetNumberField(TEXT("applied"), Applied);
		Out->SetNumberField(TEXT("failed"), Failed);
		Out->SetNumberField(TEXT("skipped"), Skipped);
		if (Skipped > 0)
		{
			Out->SetStringField(TEXT("skippedNote"), FString::Printf(
				TEXT("%d operation(s) after the failure were NOT attempted (stopOnFirstError) and have no results[] entry."),
				Skipped));
		}
		Out->SetNumberField(TEXT("rolledBack"), Rep.Undone);
		Out->SetBoolField(TEXT("dryRun"), false);
		Out->SetArrayField(TEXT("results"), Results);
		Out->SetStringField(TEXT("graphId"), GraphIdOf(Blueprint, Graph));

		if (bRollingBack)
		{
			const bool bClean = (Rep.UnresolvedPins == 0 && Rep.LostLinks == 0 && Rep.ReshapedNodes == 0);
			Out->SetBoolField(TEXT("rollbackComplete"), bClean);
			if (!bClean)
			{
				// An INCOMPLETE rollback must never be reported as a clean one. This is the failure
				// mode the whole endpoint is built to avoid, so it is stated loudly rather than folded
				// into a count.
				Out->SetNumberField(TEXT("rollbackUnresolvedPins"), Rep.UnresolvedPins);
				Out->SetNumberField(TEXT("rollbackLostLinks"), Rep.LostLinks);
				Out->SetNumberField(TEXT("rollbackReshapedNodes"), Rep.ReshapedNodes);
				TArray<TSharedPtr<FJsonValue>> Probs;
				for (const FString& P : Rep.Problems) { Probs.Add(MakeShared<FJsonValueString>(P)); }
				Out->SetArrayField(TEXT("rollbackProblems"), Probs);
			}

			// Rollback here is REAL — inverse operations replayed in reverse, not a cancelled
			// transaction (which reverts nothing; PM-007). Say which it was, because the difference
			// decides whether the caller has anything to clean up.
			Fail(Out, bClean
				? FString::Printf(
					TEXT("%s — ROLLED BACK %d already-applied operation(s) by replaying their inverses, so the graph is back to its pre-patch state. Nothing to clean up. Pass allowPartial:true to keep partial work instead."),
					*FirstError, Rep.Undone)
				: FString::Printf(
					TEXT("%s — rollback was INCOMPLETE: %d of %d operation(s) undone, %d pin(s) no longer resolvable, %d link(s) not restored, %d node(s) not returned to their previous pin shape. THE GRAPH IS NOT IN ITS PRE-PATCH STATE - read it back with list_nodes and compile before trusting it. See rollbackProblems."),
					*FirstError, Rep.Undone, Journal.Num(), Rep.UnresolvedPins, Rep.LostLinks, Rep.ReshapedNodes));
			return;
		}
		if (Failed > 0)
		{
			Out->SetStringField(TEXT("warning"), FString::Printf(
				TEXT("allowPartial was set, so %d operation(s) failed and %d were KEPT. The graph is in a partial state - read it back with list_nodes."),
				Failed, Applied));
		}
	}
}
