"""Regenerate MifBridgeDescribe.cpp's accepted-key table from the RejectUnknownParams call sites.

WHY THIS EXISTS. describe_endpoint answers "what does this endpoint accept" out of a static C++
array, GMifDescribeRows, which is harvested from the guards by hand. That array has gone stale
twice, and MifBridgeDescribe.cpp says so about itself:

    THESE THREE NUMBERS ARE A STALE ANNOTATION, NOT A FACT TO QUOTE. ... They have now gone stale
    TWICE. They read 93/95/96 at the previous harvest and were already wrong by 2 rows before this
    one began.

The cost is not cosmetic. self_audit derives paramTableCoverage from the row count, so a stale
table reports endpoints as having NO EVIDENCE of a parameter guard when the guard is right there in
the source. Measured on 2026-08-31: 217 rows against 440 live endpoints, withoutAnyEvidence 221 -
while the source held 426 RejectUnknownParams call sites for 428 MIF_DECL endpoints. Practically
every one of those 221 had a guard. An agent reading self_audit concluded 222 endpoints were
unverified territory; they were not, the bookkeeping was old.

A number nothing recomputes is a number that will be wrong again next month. This makes it derived.

WHAT IT DOES NOT DO, so the output is not over-trusted: it reports the TABLE, which is what the
source says the guard accepts. It does not prove the guard RUNS - that is fuzz_endpoints.py's
unknown-key probe, which is an independent runtime check and the thing that actually catches a
guard that is declared and unreachable. The two answer different questions and neither replaces the
other.

STRINGS ARE COPIED, NEVER RE-ENCODED. Every key, summary and note is emitted as the VERBATIM source
text between the call site's delimiters - the tool never decodes a C++ literal into a Python string
and writes it back out. Those summaries contain em dashes, escaped quotes and adjacent-literal
concatenation across lines, and a round trip through Python's idea of a string is exactly how a
generator silently mangles the text it was meant to preserve. Copying bytes cannot.

FAIL-CLOSED, the same rule parity_check.py runs on. Anything that cannot be statically resolved - a
guard in a helper reached by no endpoint, a call site whose arguments will not parse - is REPORTED
and the run fails. It is never dropped. A generator that silently omits what it cannot understand
rebuilds the exact staleness it was written to end, in a form nobody can see.

Usage:
    python tools/harvest_param_table.py            # rewrite the generated block in place
    python tools/harvest_param_table.py --check    # report drift, change nothing (exit 1 on drift)
"""
import argparse
import glob
import io
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SRC = os.path.join(ROOT, "Source", "MifBridge", "Private")
TARGET = os.path.join(SRC, "MifBridgeDescribe.cpp")
HANDLERS_H = os.path.join(SRC, "MifBridgeHandlers.h")

BEGIN = "// >>> MIF_HARVEST_BEGIN - generated by tools/harvest_param_table.py, do not hand-edit"
END = "// <<< MIF_HARVEST_END"

FUNC_DEF = re.compile(r"^\s*(?:static\s+)?(?:void|bool|int32|FString)\s+([A-Za-z_]\w*)\s*\(")
DECL = re.compile(r"^\s*MIF_DECL\((\w+)\)")


# --------------------------------------------------------------------------- source scrubbing
def blank_comments_and_strings(text):
    """A copy with comments and string bodies replaced by spaces, for LOCATING things only.

    Never used for extraction. Its only job is to stop a call site being found inside a comment -
    MifBridgeAuthoring.cpp discusses "RejectUnknownParams (the shared guard...)" in prose, and a
    naive scan reports that as an unparseable guard.
    """
    out = []
    i, n = 0, len(text)
    while i < n:
        c = text[i]
        if c == "/" and i + 1 < n and text[i + 1] == "/":
            while i < n and text[i] != "\n":
                out.append(" ")
                i += 1
        elif c == "/" and i + 1 < n and text[i + 1] == "*":
            while i < n and not (text[i] == "*" and i + 1 < n and text[i + 1] == "/"):
                out.append("\n" if text[i] == "\n" else " ")
                i += 1
            out.append("  ")
            i += 2
        elif c == '"':
            out.append(" ")
            i += 1
            while i < n:
                if text[i] == "\\":
                    out.append("  ")
                    i += 2
                    continue
                if text[i] == '"':
                    out.append(" ")
                    i += 1
                    break
                out.append("\n" if text[i] == "\n" else " ")
                i += 1
        else:
            out.append(c)
            i += 1
    return "".join(out)


def match_paren(text, open_idx):
    """Index just past the ')' closing the '(' at open_idx. Operates on scrubbed text."""
    depth = 0
    for i in range(open_idx, len(text)):
        if text[i] == "(":
            depth += 1
        elif text[i] == ")":
            depth -= 1
            if depth == 0:
                return i
    return -1


def split_args(scrubbed, raw, start, end):
    """Top-level comma split of an argument list, returned as (start, end) spans into `raw`."""
    spans, depth, a = [], 0, start
    for i in range(start, end):
        c = scrubbed[i]
        if c in "([{":
            depth += 1
        elif c in ")]}":
            depth -= 1
        elif c == "," and depth == 0:
            spans.append((a, i))
            a = i + 1
    spans.append((a, end))
    return [(s, e) for s, e in spans]


def function_spans(text, scrubbed):
    """(name, char_start, char_end) per function body, by brace depth on the scrubbed copy."""
    spans = []
    for m in re.finditer(r"^[ \t]*(?:static\s+)?(?:void|bool|int32|FString)\s+([A-Za-z_]\w*)\s*\(",
                         scrubbed, re.M):
        name = m.group(1)
        open_paren = scrubbed.find("(", m.start())
        close = match_paren(scrubbed, open_paren)
        if close < 0:
            continue
        brace = scrubbed.find("{", close)
        if brace < 0:
            continue
        # a declaration, not a definition, if a ';' comes first
        semi = scrubbed.find(";", close)
        if semi != -1 and semi < brace:
            continue
        depth, j = 0, brace
        while j < len(scrubbed):
            if scrubbed[j] == "{":
                depth += 1
            elif scrubbed[j] == "}":
                depth -= 1
                if depth == 0:
                    break
            j += 1
        spans.append((name, m.start(), j))
    return spans


def tidy(raw_text):
    """Collapse a source span to one line of C++ tokens, preserving the literals verbatim."""
    return " ".join(raw_text.split())


# --------------------------------------------------------------------------- harvest
class Unresolved(Exception):
    pass


def harvest():
    endpoints = []
    for line in io.open(HANDLERS_H, encoding="utf-8", errors="replace"):
        m = DECL.match(line)
        if m:
            endpoints.append(m.group(1))

    guards = {}          # owner function name -> dict(file, line, keys, summary, notes)
    problems = []
    calls_by_func = {}   # function name -> set of functions it calls

    for path in sorted(glob.glob(os.path.join(SRC, "*.cpp"))):
        base = os.path.basename(path)
        raw = io.open(path, encoding="utf-8", errors="replace").read()
        scrub = blank_comments_and_strings(raw)
        spans = function_spans(raw, scrub)

        for name, a, b in spans:
            body = scrub[a:b]
            # THE TEMPLATE ARGUMENT LIST IS PART OF THE CALL. SpawnDelegateNode is a template and
            # every caller writes SpawnDelegateNode<UK2Node_CallDelegate>(In, Out), so a pattern
            # expecting '(' straight after the name finds no caller at all - and the two dispatcher
            # endpoints it guards get reported as unguarded when the guard is right there.
            calls_by_func.setdefault(name, set()).update(
                re.findall(r"\b([A-Za-z_]\w*)\s*(?:<[^;{}()<>]*>)?\s*\(", body))

        for m in re.finditer(r"\bRejectUnknownParams\s*\(", scrub):
            # the definition itself, not a call
            if base == "MifBridgeCommon.cpp":
                tail = scrub[m.end():m.end() + 220]
                if "std::initializer_list" in tail:
                    continue
            open_paren = scrub.find("(", m.start())
            close = match_paren(scrub, open_paren)
            if close < 0:
                problems.append("%s: unbalanced parens at offset %d" % (base, m.start()))
                continue
            args = split_args(scrub, raw, open_paren + 1, close)
            if len(args) < 4:
                problems.append("%s:%d: RejectUnknownParams with %d args, expected 4 or 5"
                                % (base, raw[:m.start()].count("\n") + 1, len(args)))
                continue

            owner = None
            for fname, fa, fb in spans:
                if fa <= m.start() <= fb:
                    owner = fname
            if owner is None:
                problems.append("%s:%d: guard is in no function body"
                                % (base, raw[:m.start()].count("\n") + 1))
                continue

            keys = tidy(raw[args[2][0]:args[2][1]])
            summary = tidy(raw[args[3][0]:args[3][1]])
            notes = tidy(raw[args[4][0]:args[4][1]]) if len(args) >= 5 else ""
            guards[owner] = {
                "file": base,
                "line": raw[:m.start()].count("\n") + 1,
                "keys": keys.strip().lstrip("{").rstrip("}").strip(),
                "summary": summary,
                "notes": notes.strip().lstrip("{").rstrip("}").strip(),
            }

    # ------------------------------------------------------- endpoint -> guard
    rows, missing = [], []
    for ep in endpoints:
        direct = guards.get("H_" + ep)
        if direct:
            rows.append((ep, direct, None))
            continue
        # a guard reached through a shared helper the handler calls
        called = calls_by_func.get("H_" + ep, set())
        via = [h for h in called if h in guards and not h.startswith("H_")]
        if len(via) == 1:
            rows.append((ep, guards[via[0]], via[0]))
        elif len(via) > 1:
            problems.append("%s: reaches %d guarded helpers (%s) - cannot choose one"
                            % (ep, len(via), ", ".join(sorted(via))))
        else:
            missing.append(ep)
    return rows, missing, problems, endpoints


# --------------------------------------------------------------------------- emit
def ident(ep):
    return re.sub(r"\W", "_", ep)


def render(rows):
    out = [BEGIN,
           "\t\t// %d endpoints, harvested from the RejectUnknownParams call site that guards each."
           % len(rows),
           "\t\t// Regenerate with tools/harvest_param_table.py; every string below is the VERBATIM",
           "\t\t// source text of the guard, copied rather than re-encoded.",
           ""]
    for ep, g, via in rows:
        # Skipped for the same reason its row is: GMifDescKeys_describe_endpoint and its notes are
        # defined ABOVE this block, from MIF_DESCRIBE_OWN_KEYS, shared with the guard in the handler.
        # Emitting them here is a redefinition, which the compiler catches (C2374) - unlike the
        # duplicate ROW, which compiled fine and only inflated the count.
        if ep == "describe_endpoint":
            continue
        i = ident(ep)
        out.append("\t\tstatic const TCHAR* const GMifDescKeys_%s[] = { %s%snullptr };"
                   % (i, g["keys"], ", " if g["keys"] else ""))
        if g["notes"]:
            out.append("\t\tstatic const TCHAR* const GMifDescNotes_%s[] = { %s, nullptr };"
                       % (i, re.sub(r"\}\s*,\s*\{", ", ", g["notes"]).strip().lstrip("{").rstrip("}").strip()))
    out.append("")
    out.append("\t\tstatic const FMifDescribeRow GMifDescribeRows[] = {")
    out.append("\t\t\t{ TEXT(\"describe_endpoint\"), GMifDescKeys_describe_endpoint, "
               "GMifDescNotes_describe_endpoint,")
    out.append("\t\t\t  MIF_DESCRIBE_OWN_SUMMARY,")
    out.append("\t\t\t  TEXT(\"MifBridgeDescribe.cpp\"), 0, nullptr },")
    for ep, g, via in rows:
        # describe_endpoint is emitted BY HAND above, deliberately, sharing MIF_DESCRIBE_OWN_KEYS
        # with the guard in its own handler so the endpoint that reports parameter sets cannot
        # misreport its own. Emitting it here too gave two rows for it: harmless to the linear
        # lookup, which returns the first, but it inflated MifDescribeParamRowCount by one - and a
        # row count that is off by one is exactly the kind of quiet wrongness this tool exists to
        # stop.
        if ep == "describe_endpoint":
            continue
        i = ident(ep)
        notes = ("GMifDescNotes_%s" % i) if g["notes"] else "nullptr"
        out.append("\t\t\t{ TEXT(\"%s\"), GMifDescKeys_%s, %s," % (ep, i, notes))
        out.append("\t\t\t  %s," % g["summary"])
        out.append("\t\t\t  TEXT(\"%s\"), %d, %s },"
                   % (g["file"], g["line"], ("TEXT(\"%s\")" % via) if via else "nullptr"))
    out.append("\t\t};")
    out.append(END)
    return "\n".join(out)


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true", help="report drift, change nothing")
    a = ap.parse_args()

    rows, missing, problems, endpoints = harvest()

    print("endpoints declared (MIF_DECL) : %d" % len(endpoints))
    print("guards resolved to an endpoint: %d" % len(rows))
    print("endpoints with NO guard found : %d" % len(missing))
    if missing:
        # NAMED, never counted. These are the endpoints that genuinely accept anything silently -
        # the output of this tool, not noise to be tolerated.
        for ep in missing:
            print("    no RejectUnknownParams: %s" % ep)
    if problems:
        print("")
        print("UNRESOLVED - the table was NOT written, because a generator that drops what it")
        print("cannot parse rebuilds the staleness it exists to end:")
        for p in problems:
            print("    " + p)
        return 1

    body = render(rows)
    src = io.open(TARGET, encoding="utf-8", errors="replace").read()
    if BEGIN in src and END in src:
        head = src[:src.index(BEGIN)]
        tail = src[src.index(END) + len(END):]
        new = head + body + tail
    else:
        print("")
        print("MARKERS NOT FOUND in %s." % os.path.basename(TARGET))
        print("Add these two lines around the generated region once, then re-run:")
        print("    %s" % BEGIN)
        print("    %s" % END)
        return 2

    if a.check:
        if new == src:
            print("\ntable is up to date with the guards")
            return 0
        # CONTRACT DRIFT AND PROVENANCE DRIFT ARE NOT THE SAME FAILURE. Any edit above a guard
        # shifts the source LINE of every guard below it in that file, so a comment change is
        # enough to make the whole table differ - and a packaging gate that fires on comment edits
        # is one people learn to --force past. Compare with the line numbers normalised away: what
        # is left is the endpoint, its keys, its summary, its notes and its file, which is
        # everything describe_endpoint promises a caller.
        strip_lines = lambda t: re.sub(r'(TEXT\("Mif\w+\.cpp"\), )\d+', r"\g<1>0", t)
        if strip_lines(new) == strip_lines(src):
            moved = sum(1 for x, y in zip(new.splitlines(), src.splitlines()) if x != y)
            print("\ntable matches the guards; %d line citation(s) have moved." % moved)
            print("Not a release blocker - the accepted keys, summaries and notes are unchanged,")
            print("and only the source line each row cites is out of date. Regenerate when")
            print("convenient: tools/harvest_param_table.py")
            return 0
        print("\nCONTRACT DRIFT: the committed table does not describe the guards in the source.")
        print("An endpoint's accepted keys, summary, notes or file has changed, so describe_endpoint")
        print("is telling callers something the guard does not do.")
        print("Run tools/harvest_param_table.py to regenerate, then rebuild.")
        return 1

    if new == src:
        print("\ntable already up to date - nothing written")
        return 0
    io.open(TARGET, "w", encoding="utf-8", newline="\r\n").write(new)
    print("\nwrote %d rows into %s" % (len(rows), os.path.basename(TARGET)))
    print("REBUILD REQUIRED - the table is compiled into the DLL.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
