"""Generate a throwaway UE project whose ONLY purpose is to compile MifBridge against a given engine.

WHY THIS EXISTS
---------------
This plugin's release manifest claims two engines. Until tonight that claim rested entirely on
READING headers - comparing the 5.3 and 5.7 source trees by eye and reasoning about what would
compile. A second session synced the plugin into a real 5.7 project and found six defects in an
hour, one of which no amount of reading had caught, because the two declarations look
interchangeable until a compiler disagrees.

Reading finds symbols that were DELETED. It reliably misses symbols that CHANGED SHAPE. The
clearest example is in this plugin's own IK Rig support:

    5.3: int32 AddSolver(TSubclassOf<UIKRigSolver> InSolverClass) const;
    5.7: int32 AddSolver(const FString InIKRigSolverType) const;

Same name, same arity, same return type, present in both trees. Every presence-based check passes.
It cannot compile.

So: stop reasoning about it and run a compiler. This builds a minimal project around the plugin -
one module, no content, nothing to open - purely so UnrealBuildTool has something to hang the
plugin off. The plugin SOURCE is junctioned rather than copied, so the probe compiles canonical
source directly and a fix lands in the real file rather than in a copy that drifts. Only Source/ -
see link_plugin() for what junctioning the plugin ROOT did to a working editor.

The probe directory is disposable. This script is the thing worth keeping.

TWO TRAPS ON THIS MACHINE, both learned the expensive way:

1. TOOLCHAIN. The DDS2 5.3.2 cooked-editor fork requires MSVC 14.36.32532 exactly (it lives in
   C:/BT176). UE 5.7 cannot build with 14.36. If a global UBT pin ever forces that toolchain -
   %APPDATA%/Unreal Engine/UnrealBuildTool/BuildConfiguration.xml - a 5.7 build fails in a way that
   looks like a source problem and is not. The generated target sets CompilerVersion explicitly so
   the two engines stay independent, and so that file never needs editing.

2. THE EXIT CODE LIES. Same rule as every other build in this repo: check that the binary's mtime
   actually moved. A "success" that took under a second did nothing.
"""
import argparse
import io
import json
import os
import shutil
import subprocess
import sys

NL = "\n"
CANONICAL = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))


def write(path, text):
    """Every file this repo writes is CRLF. C# and .uproject are no exception."""
    os.makedirs(os.path.dirname(path), exist_ok=True)
    io.open(path, "wb").write(text.replace(NL, "\r\n").encode("utf-8"))


def generate(root, module, engine_assoc):
    uproject = {
        "FileVersion": 3,
        "EngineAssociation": engine_assoc,
        "Category": "",
        "Description": "Throwaway compile probe for MifBridge, generated by "
                       "tools/make_engine_probe.py. Do not open it, do not add content, do not "
                       "commit it. Delete freely.",
        "Modules": [{"Name": module, "Type": "Runtime", "LoadingPhase": "Default"}],
        # MifBridge is an Editor module, so only the Editor target builds it. That is the point:
        # the probe exists to compile the plugin, and there is nothing else here to compile.
        "Plugins": [{"Name": "MifBridge", "Enabled": True}],
    }
    write(os.path.join(root, module + ".uproject"), json.dumps(uproject, indent=2) + NL)

    TARGET_NOTE = NL.join([
        "\t\t// This machine has TWO engines with incompatible toolchain requirements: the DDS2 5.3.2",
        "\t\t// cooked-editor fork at D:/UE532 needs MSVC 14.36.32532 (C:/BT176), and UE 5.7 cannot",
        "\t\t// build with it. Setting this explicitly means a global UBT pin - one exists at",
        "\t\t// %APPDATA%/Unreal Engine/UnrealBuildTool/BuildConfiguration.xml and must NOT be edited,",
        "\t\t// because the DDS2 modding builds depend on it - cannot silently break this probe.",
        "\t\tWindowsPlatform.CompilerVersion = " + chr(34) + "Latest" + chr(34) + ";",
    ])

    for suffix, ttype in (("", "Game"), ("Editor", "Editor")):
        cls = module + suffix + "Target"
        write(os.path.join(root, "Source", module + suffix + ".Target.cs"), NL.join([
            "// Generated by MifBridge/tools/make_engine_probe.py. Disposable.",
            "using UnrealBuildTool;",
            "",
            "public class " + cls + " : TargetRules",
            "{",
            "\tpublic " + cls + "(TargetInfo Target) : base(Target)",
            "\t{",
            "\t\tType = TargetType." + ttype + ";",
            "\t\t// Latest on BOTH engines, deliberately. The probe should hold the plugin to the",
            "\t\t// strictest settings the engine offers - a compatibility check that quietly relaxes",
            "\t\t// the rules is measuring the wrong thing.",
            "\t\tDefaultBuildSettings = BuildSettingsVersion.Latest;",
            "\t\tIncludeOrderVersion = EngineIncludeOrderVersion.Latest;",
            TARGET_NOTE,
            "\t\tExtraModuleNames.Add(" + chr(34) + module + chr(34) + ");",
            "\t}",
            "}",
            "",
        ]))

    q = chr(34)
    write(os.path.join(root, "Source", module, module + ".Build.cs"), NL.join([
        "// Generated by MifBridge/tools/make_engine_probe.py. Disposable.",
        "using UnrealBuildTool;",
        "",
        "public class " + module + " : ModuleRules",
        "{",
        "\tpublic " + module + "(ReadOnlyTargetRules Target) : base(Target)",
        "\t{",
        "\t\tPCHUsage = PCHUsageMode.UseExplicitOrSharedPCHs;",
        "\t\tPublicDependencyModuleNames.AddRange(new string[] { " + q + "Core" + q + ", "
        + q + "CoreUObject" + q + ", " + q + "Engine" + q + " });",
        "\t}",
        "}",
        "",
    ]))

    write(os.path.join(root, "Source", module, module + ".h"), NL.join([
        "#pragma once", "", "#include " + q + "CoreMinimal.h" + q, "",
    ]))
    write(os.path.join(root, "Source", module, module + ".cpp"), NL.join([
        "#include " + q + module + ".h" + q,
        "#include " + q + "Modules/ModuleManager.h" + q,
        "",
        "// The probe needs a primary game module to be a valid code project. It does nothing else.",
        "IMPLEMENT_PRIMARY_GAME_MODULE(FDefaultGameModuleImpl, " + module + ", "
        + q + module + q + ");",
        "",
    ]))


def link_plugin(root):
    """Junction the SOURCE directory only - never the plugin root.

    The first version of this junctioned the whole plugin folder, which is wrong in a way that took a
    working editor down to find. UnrealBuildTool writes a plugin's compiled output to
    <Project>/Plugins/<Name>/Binaries and its object files to .../Intermediate. With the plugin ROOT
    junctioned, both of those resolve back into the canonical folder - so building the probe against
    5.7 overwrote the 5.3 UnrealEditor-MifBridge.dll that the SDK editor loads, with a binary that
    engine cannot load at all, and left 62 5.7 object files in the canonical Intermediate.

    Nothing warned. The build reported success, because from its point of view it had succeeded.

    Junctioning Source/ alone keeps the live-source property that made a junction the right choice -
    a fix lands in the real file, no copy to drift - while Binaries/ and Intermediate/ are created
    inside the disposable probe where they belong. The .uplugin is COPIED rather than linked because
    it is one small file that never changes during a build, and because a junction to a file is a
    different beast from a junction to a directory."""
    plugin_dir = os.path.join(root, "Plugins", "MifBridge")
    src_link = os.path.join(plugin_dir, "Source")
    os.makedirs(plugin_dir, exist_ok=True)

    descriptor = os.path.join(CANONICAL, "MifBridge.uplugin")
    shutil.copyfile(descriptor, os.path.join(plugin_dir, "MifBridge.uplugin"))

    if os.path.exists(src_link):
        return "Source already linked"
    r = subprocess.run(["cmd", "/c", "mklink", "/J", src_link,
                        os.path.join(CANONICAL, "Source")],
                       capture_output=True, text=True)
    if r.returncode != 0:
        raise SystemExit("mklink failed: " + (r.stderr or r.stdout))
    return "Source junction -> " + os.path.join(CANONICAL, "Source") + "  (Binaries/Intermediate stay local)"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--engine", required=True,
                    help="engine root, e.g. 'C:/Program Files/Epic Games/UE_5.7'")
    ap.add_argument("--out", required=True, help="where to generate the probe project")
    ap.add_argument("--module", default="MifProbe")
    ap.add_argument("--assoc", default="5.7")
    ap.add_argument("--build", action="store_true", help="run the build after generating")
    a = ap.parse_args()

    root = os.path.abspath(a.out)
    generate(root, a.module, a.assoc)
    print("generated  " + root)
    print("plugin     " + link_plugin(root))

    bat = os.path.join(a.engine, "Engine", "Build", "BatchFiles", "Build.bat")
    if not os.path.isfile(bat):
        raise SystemExit("no Build.bat at " + bat)
    cmd = [bat, a.module + "Editor", "Win64", "Development",
           "-Project=" + os.path.join(root, a.module + ".uproject"), "-WaitMutex"]
    print("build      " + subprocess.list2cmdline(cmd))
    if a.build:
        sys.exit(subprocess.run(cmd).returncode)


if __name__ == "__main__":
    main()
