"""apply_graph_patch regression suite.

The two tests that actually matter are T7 and T8 - they are the ones that prove the hardening,
because they exercise engine behaviour that a naive inverse gets WRONG:

  T7  connecting to an already-connected single-link exec pin SILENTLY BREAKS the old wire
      (CONNECT_RESPONSE_BREAK_OTHERS_*). A rollback that only breaks the new link leaves the old
      one destroyed while reporting success.
  T8  connecting to an input pin WIPES its default value
      (UK2Node::PinConnectionListChanged -> ResetPinToAutogeneratedDefaultValue). A rollback that
      restores links but not defaults silently loses it.

Everything else is scaffolding to get a graph into a state where those two can be checked.
"""
import json
import sys
import time
import urllib.error
import urllib.request

BASE = "http://127.0.0.1:8791/api"
TOKEN = "dev"

PASS, FAIL = [], []


def post(_ep, **payload):
    body = json.dumps({k: v for k, v in payload.items() if v is not None}).encode("utf-8")
    req = urllib.request.Request(
        BASE + "/" + _ep, data=body,
        headers={"X-Mif-Token": TOKEN, "Content-Type": "application/json"})
    try:
        with urllib.request.urlopen(req, timeout=120) as r:
            return json.loads(r.read().decode("utf-8"))
    except urllib.error.HTTPError as e:
        try:
            return json.loads(e.read().decode("utf-8"))
        except Exception:
            return {"ok": False, "error": "HTTP %s" % e.code}
    except Exception as e:
        return {"ok": False, "error": "unreachable: %s" % e}


def check(name, cond, detail=""):
    if cond:
        PASS.append(name)
        print("  PASS  %s" % name)
    else:
        FAIL.append((name, detail))
        print("  FAIL  %s   %s" % (name, detail))


def wait_for_bridge(timeout=600):
    print("waiting for bridge...")
    start = time.time()
    while time.time() - start < timeout:
        r = post("self_audit", summaryOnly=True)
        if r.get("ok"):
            print("bridge up: %d endpoints, built %s %s"
                  % (r.get("endpointCount", -1), r.get("buildDate"), r.get("buildTime")))
            return r
        time.sleep(5)
    print("bridge never came up")
    sys.exit(1)


def _node(node_guid):
    """get_node nests everything under "node" - reading the top level silently yields nothing,
    which is how the first run of this suite produced two VACUOUS passes (None == None)."""
    r = post("get_node", nodeGuid=node_guid)
    return r.get("node") if r.get("ok") else None


def _pin(node_guid, pin_name):
    nd = _node(node_guid)
    if not nd:
        return None
    for p in nd.get("pins", []):
        if p.get("name", "").lower() == pin_name.lower():
            return p
    return None


def links_of(node_guid, pin_name):
    """Sorted [(nodeGuid, pinName)] this pin links to. linkedTo entries are {"node","pin"}."""
    p = _pin(node_guid, pin_name)
    if p is None:
        return None
    return sorted((l.get("node", ""), l.get("pin", "")) for l in (p.get("linkedTo") or []))


def default_of(node_guid, pin_name):
    """The pin default. The field is "default" - NOT "defaultValue". A pin with no default
    simply has no key, so absent is reported as "" rather than None."""
    p = _pin(node_guid, pin_name)
    if p is None:
        return None
    return p.get("default", "")


def graph_fingerprint(graph_id):
    """Every link in the graph, sorted. Two identical fingerprints == identical wiring."""
    r = post("list_nodes", graphId=graph_id)
    if not r.get("ok"):
        return None
    edges = []
    for n in r.get("nodes", []):
        g = n.get("guid", "")
        for p in n.get("pins", []) or []:
            for l in p.get("linkedTo") or []:
                a = (g, p.get("name", ""))
                b = (l.get("node", ""), l.get("pin", ""))
                edges.append(tuple(sorted([a, b])))
    return sorted(set(edges))


def assert_probe(graph_id, node_guid, pin_name):
    """Prove the helpers actually SEE something before any test relies on them. Without this a
    typo'd field name turns every comparison into None==None and the suite reports success."""
    if default_of(node_guid, pin_name) is None:
        print("PROBE FAILED: default_of returned None - helper field names are wrong")
        sys.exit(4)
    if links_of(node_guid, "execute") is None:
        print("PROBE FAILED: links_of returned None - helper field names are wrong")
        sys.exit(4)
    if graph_fingerprint(graph_id) is None:
        print("PROBE FAILED: graph_fingerprint returned None")
        sys.exit(4)
    print("helper probe OK")


# ==============================================================================
audit = wait_for_bridge()
HAS_PATCH = False
d = post("describe_endpoint", endpoint="apply_graph_patch")
HAS_PATCH = bool(d.get("ok"))
print("apply_graph_patch present: %s" % HAS_PATCH)
if not HAS_PATCH:
    print("ENDPOINT MISSING - the editor is running an old DLL. Aborting.")
    sys.exit(2)

# Per-RUN unique. A fixed scratch path passes once and fails every time after, because unsaved
# scratch assets live until the editor process ends - so this was green all night and failed
# the moment a full suite run happened twice without a restart in between.
BP = "/Game/_MifPatchTest/BP_PatchTest_%d" % int(time.time() % 100000)
print("\n=== setup: create test blueprint ===")
post("delete_asset", path=BP, confirm=True)   # clean slate; ignore result
bp = post("create_blueprint", path=BP, parentClass="Actor")
if not bp.get("ok"):
    print("could not create blueprint:", bp)
    sys.exit(3)
BPID = bp.get("blueprintId") or bp.get("objectPath")
print("blueprintId:", BPID)

# A fresh Actor Blueprint ALREADY has BeginPlay, so add_override_event refuses it. Take whichever
# path yields a node: create it, or find the one that is already there.
ev = post("add_override_event", blueprintId=BPID, event="ReceiveBeginPlay")
GRAPH = ev.get("graphId")
EVENT = ev.get("nodeGuid")
if not GRAPH or not EVENT:
    GRAPH = BPID + "::EventGraph"
    ln = post("list_nodes", graphId=GRAPH)
    for nd in ln.get("nodes", []):
        title = (nd.get("title") or "") + " " + (nd.get("name") or "") + " " + (nd.get("class") or "")
        if "BeginPlay" in title:
            EVENT = nd.get("guid") or nd.get("nodeGuid")
            break
print("graphId:", GRAPH, " event:", EVENT)
if not GRAPH or not EVENT:
    print("could not resolve event graph. add_override_event said:", ev)
    print("list_nodes said:", json.dumps(post("list_nodes", graphId=GRAPH))[:900])
    sys.exit(3)

# Three delay-ish call nodes to wire into an exec chain.
n = []
for i in range(3):
    r = post("add_function_call", graphId=GRAPH, function="PrintString",
             **{"class": "KismetSystemLibrary"}, x=400 + 300 * i, y=0)
    if not r.get("ok"):
        print("could not add node %d: %s" % (i, r))
        sys.exit(3)
    n.append(r.get("nodeGuid"))
print("nodes:", n)
assert_probe(GRAPH, n[0], "InString")

# ==============================================================================
print("\n=== T1: dryRun mutates nothing ===")
before = graph_fingerprint(GRAPH)
r = post("apply_graph_patch", graphId=GRAPH, dryRun=True, operations=[
    {"op": "connect_pins", "srcNode": EVENT, "srcPin": "then", "dstNode": n[0], "dstPin": "execute"},
    {"op": "connect_pins", "srcNode": n[0], "srcPin": "then", "dstNode": n[1], "dstPin": "execute"},
])
check("T1 dryRun ok", r.get("ok") is True, json.dumps(r)[:200])
check("T1 dryRun flag echoed", r.get("dryRun") is True)
check("T1 applied==0", r.get("applied") == 0)
check("T1 graph untouched", graph_fingerprint(GRAPH) == before)

print("\n=== T2: multi-op patch applies ===")
r = post("apply_graph_patch", graphId=GRAPH, operations=[
    {"op": "connect_pins", "srcNode": EVENT, "srcPin": "then", "dstNode": n[0], "dstPin": "execute"},
    {"op": "connect_pins", "srcNode": n[0], "srcPin": "then", "dstNode": n[1], "dstPin": "execute"},
    {"op": "set_pin_default", "node": n[0], "pin": "InString", "value": "FIRST"},
    {"op": "set_pin_default", "node": n[1], "pin": "InString", "value": "SECOND"},
])
check("T2 ok", r.get("ok") is True, json.dumps(r)[:300])
check("T2 applied==4", r.get("applied") == 4, str(r.get("applied")))
check("T2 default landed", default_of(n[0], "InString") == "FIRST",
      repr(default_of(n[0], "InString")))
check("T2 link landed", (n[0], "execute") in [tuple(x) for x in (links_of(EVENT, "then") or [])]
      or len(links_of(EVENT, "then") or []) == 1)

WIRED = graph_fingerprint(GRAPH)

print("\n=== T3: preflight refuses a bad op WITHOUT touching the graph ===")
r = post("apply_graph_patch", graphId=GRAPH, operations=[
    {"op": "set_pin_default", "node": n[2], "pin": "InString", "value": "SHOULD_NOT_LAND"},
    {"op": "connect_pins", "srcNode": "00000000-0000-0000-0000-000000000000",
     "srcPin": "then", "dstNode": n[2], "dstPin": "execute"},
])
check("T3 refused", r.get("ok") is False, json.dumps(r)[:200])
check("T3 applied==0", r.get("applied") == 0)
check("T3 nothing landed", default_of(n[2], "InString") != "SHOULD_NOT_LAND",
      repr(default_of(n[2], "InString")))
check("T3 graph unchanged", graph_fingerprint(GRAPH) == WIRED)

print("\n=== T4: unknown key inside an operation is refused, not ignored ===")
r = post("apply_graph_patch", graphId=GRAPH, operations=[
    {"op": "set_pin_default", "node": n[2], "pin": "InString", "value": "X", "typo_key": "boom"},
])
check("T4 refused", r.get("ok") is False, json.dumps(r)[:200])
check("T4 names the key", "typo_key" in json.dumps(r), json.dumps(r)[:300])

print("\n=== T5: mid-sequence failure rolls the whole patch back ===")
before5 = graph_fingerprint(GRAPH)
d0 = default_of(n[0], "InString")
r = post("apply_graph_patch", graphId=GRAPH, allowPartial=False, operations=[
    {"op": "set_pin_default", "node": n[0], "pin": "InString", "value": "CHANGED_1"},
    {"op": "connect_pins", "srcNode": n[1], "srcPin": "then", "dstNode": n[2], "dstPin": "execute"},
    {"op": "set_pin_default", "node": n[2], "pin": "NoSuchPin_XYZ", "value": "nope"},
])
check("T5 failed overall", r.get("ok") is False, json.dumps(r)[:200])
check("T5 graph restored exactly", graph_fingerprint(GRAPH) == before5,
      "fingerprint drift after rollback")
check("T5 default restored", default_of(n[0], "InString") == d0,
      "was %r now %r" % (d0, default_of(n[0], "InString")))

print("\n=== T6: allowPartial keeps partial work and says so ===")
before6 = graph_fingerprint(GRAPH)
r = post("apply_graph_patch", graphId=GRAPH, allowPartial=True, stopOnFirstError=False, operations=[
    {"op": "set_pin_default", "node": n[2], "pin": "InString", "value": "PARTIAL_OK"},
    {"op": "set_pin_default", "node": n[2], "pin": "NoSuchPin_XYZ", "value": "nope"},
])
check("T6 kept the good op", default_of(n[2], "InString") == "PARTIAL_OK",
      repr(default_of(n[2], "InString")))
check("T6 warned about partial state", "warning" in r or r.get("failed", 0) > 0, json.dumps(r)[:200])
post("set_pin_default", node=n[2], pin="InString", value="")   # reset

# T7 AND T8 ARE PREFLIGHT TESTS, NOT ROLLBACK TESTS - corrected 2026-08-31.
#
# Both use a nonexistent pin as the failing op, and a nonexistent pin is caught at PREFLIGHT: the
# patch is refused before anything is applied. So "the displaced link came back" was trivially true
# over a graph that was never touched, and "rollbackComplete true" was asserted as `is not False`,
# which passes when the field is ABSENT - which it is, because no rollback ran.
#
# test_rollback_real.py exists precisely because of this and says so in its own docstring. It reaches
# a real mid-apply failure with a tripwire that is legal at preflight and illegal by the time it
# runs, and it is where the rollback assertions belong. These two now assert the property they
# actually exercise: preflight refuses, and the graph is untouched.
print("\n=== T7: preflight refuses before applying, so the displaced link never moved ===")
# EVENT.then is already wired to n[0]. Connecting EVENT.then -> n[2] displaces that wire.
# Then a deliberate failure must bring the ORIGINAL EVENT.then -> n[0] link back.
orig = links_of(EVENT, "then")
print("  EVENT.then before:", orig)
r = post("apply_graph_patch", graphId=GRAPH, allowPartial=False, operations=[
    {"op": "connect_pins", "srcNode": EVENT, "srcPin": "then", "dstNode": n[2], "dstPin": "execute"},
    {"op": "set_pin_default", "node": n[0], "pin": "NoSuchPin_XYZ", "value": "force failure"},
])
after = links_of(EVENT, "then")
print("  EVENT.then after rollback:", after)
check("T7 patch failed as designed", r.get("ok") is False)
check("T7 NOTHING was applied - the failing op is caught at preflight, so this exercises the "
      "refusal path and not the rollback path (see test_rollback_real.py for that)",
      r.get("applied", 0) == 0 and r.get("rolledBack", 0) == 0,
      "applied=%s rolledBack=%s: %s" % (r.get("applied"), r.get("rolledBack"), json.dumps(r)[:220]))
check("T7 and the link is where it started, because nothing ever touched it", after == orig,
      "orig %s != after %s" % (orig, after))

print("\n=== T8: same shape - preflight refuses, so the default was never wiped ===")
# Give n[2].InString a default, then connect something INTO that pin. The engine wipes the default
# via ResetPinToAutogeneratedDefaultValue. A rollback must put it back.
post("set_pin_default", node=n[2], pin="InString", value="DEFAULT_TO_PRESERVE")
d_before = default_of(n[2], "InString")
print("  n2.InString before:", repr(d_before))
# add a string variable to wire into it
post("add_variable", blueprintId=BPID, name="PatchTestStr", type="string")
gv = post("add_variable_get", graphId=GRAPH, variable="PatchTestStr", x=200, y=400)
GV = gv.get("nodeGuid")
if GV:
    r = post("apply_graph_patch", graphId=GRAPH, allowPartial=False, operations=[
        {"op": "connect_pins", "srcNode": GV, "srcPin": "PatchTestStr",
         "dstNode": n[2], "dstPin": "InString"},
        {"op": "set_pin_default", "node": n[2], "pin": "NoSuchPin_XYZ", "value": "force failure"},
    ])
    d_after = default_of(n[2], "InString")
    print("  n2.InString after rollback:", repr(d_after))
    check("T8 patch failed as designed", r.get("ok") is False, json.dumps(r)[:200])
    check("T8 the default is untouched, because preflight refused before the connect ran - not "
          "because a rollback restored it (test_rollback_real.py proves the restore)",
          d_after == d_before and r.get("applied", 0) == 0,
          "before %r != after %r, applied=%s" % (d_before, d_after, r.get("applied")))
else:
    print("  (skipped - could not add variable getter: %s)" % json.dumps(gv)[:150])

print("\n=== T9: compile the result ===")
c = post("compile", blueprintId=BPID)
check("T9 compiles", c.get("ok") is True and c.get("numErrors", 1) == 0,
      "errors=%s msgs=%s" % (c.get("numErrors"), json.dumps(c.get("messages", []))[:300]))
check("T9 reports savedToDisk:false", c.get("savedToDisk") is False, str(c.get("savedToDisk")))

# ==============================================================================
print("\n=== cleanup ===")
print(json.dumps(post("delete_asset", path=BP, confirm=True))[:200])

print("\n" + "=" * 70)
print("PASS %d   FAIL %d" % (len(PASS), len(FAIL)))
for name, detail in FAIL:
    print("  FAILED: %s\n          %s" % (name, detail))
print("=" * 70)
sys.exit(1 if FAIL else 0)
